from ...doc import *

cuSPARSE_extra = [
# 9.1. cusparse<t>csrgeam()
  func_decl( [ "cusparseXcsrgeamNnz" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('descrB', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzB', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedRowPtrB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('nnzTotalDevHostPtr', [ MEMORY_HOST, SCALAR ], INOUT_OUT ) ] ),

  func_decl( [ "cusparseScsrgeam", "cusparseDcsrgeam", "cusparseCcsrgeam", "cusparseZcsrgeam" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('descrB', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzB', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtrB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrSortedRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrSortedColIndC', MEMORY_DEVICE, INOUT_OUT ) ] ),

# 9.2. cusparse<t>csrgeam2() # seems to be just part of CUDA LIB 9.2
  func_decl( [ "cusparseScsrgeam2_bufferSizeExt", "cusparseDcsrgeam2_bufferSizeExt", "cusparseCcsrgeam2_bufferSizeExt", "cusparseZcsrgeam2_bufferSizeExt" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('descrB', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzB', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtrB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrSortedRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrSortedColIndC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('pBufferSizeInBytes', [ MEMORY_HOST, SCALAR ], INOUT_OUT, { "typepatch" : "size_t *" } ) ] ), # lives on host

  func_decl( [ "cusparseXcsrgeam2Nnz" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('descrB', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzB', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedRowPtrB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('nnzTotalDevHostPtr', [ MEMORY_HOST, SCALAR ], INOUT_OUT ),
               parm_def('workspace', PASSBYVALUE, INOUT_IN ) ] ),

  func_decl( [ "cusparseScsrgeam2", "cusparseDcsrgeam2", "cusparseCcsrgeam2", "cusparseZcsrgeam2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('descrB', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzB', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtrB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrSortedRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrSortedColIndC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ) ] ),

# 9.3. cusparse<t>csrgemm()
  func_decl( [ "cusparseXcsrgemmNnz" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('transA', PASSBYVALUE, INOUT_IN ),
               parm_def('transB', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('k', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('descrB', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzB', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedRowPtrB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('nnzTotalDevHostPtr', [ MEMORY_HOST, SCALAR ], INOUT_OUT ) ] ),

  func_decl( [ "cusparseScsrgemm", "cusparseDcsrgemm", "cusparseCcsrgemm", "cusparseZcsrgemm" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('transA', PASSBYVALUE, INOUT_IN ),
               parm_def('transB', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('k', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('descrB', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzB', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtrB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrSortedRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrSortedColIndC', MEMORY_DEVICE, INOUT_OUT ) ] ),

# 9.4. cusparse<t>csrgemm2()
  func_decl( [ "cusparseScsrgemm2_bufferSizeExt", "cusparseDcsrgemm2_bufferSizeExt", "cusparseCcsrgemm2_bufferSizeExt", "cusparseZcsrgemm2_bufferSizeExt" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('k', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('descrB', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzB', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedRowPtrB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('descrD', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzD', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedRowPtrD', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndD', MEMORY_DEVICE, INOUT_IN ),
               parm_def('info', PASSBYVALUE, INOUT_IN ),
               parm_def('pBufferSizeInBytes', [ MEMORY_HOST, SCALAR ], INOUT_OUT, { "typepatch" : "size_t *" } ) ] ), # lives on host

  func_decl( [ "cusparseXcsrgemm2Nnz" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('k', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('descrB', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzB', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedRowPtrB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('descrD', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzD', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedRowPtrD', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndD', MEMORY_DEVICE, INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrSortedColIndC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('nnzTotalDevHostPtr', [ MEMORY_HOST, SCALAR ], INOUT_OUT ),
               parm_def('info', PASSBYVALUE, INOUT_IN ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ) ] ),

  func_decl( [ "cusparseScsrgemm2", "cusparseDcsrgemm2", "cusparseCcsrgemm2", "cusparseZcsrgemm2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('k', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('descrB', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzB', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtrB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndB', MEMORY_DEVICE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('descrD', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzD', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValD', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtrD', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndD', MEMORY_DEVICE, INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrSortedRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrSortedColIndC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('info', PASSBYVALUE, INOUT_IN ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ) ] ),


]
