from ...doc import *

cuSPARSE_format = [
# 12.1. cusparse<t>bsr2csr()
  func_decl( [ "cusparseSbsr2csr", "cusparseDbsr2csr", "cusparseCbsr2csr", "cusparseZbsr2csr" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('dirA', PASSBYVALUE, INOUT_IN ),
               parm_def('mb', PASSBYVALUE, INOUT_IN ),
               parm_def('nb', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('bsrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('blockDim', PASSBYVALUE, INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrSortedRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrSortedColIndC', MEMORY_DEVICE, INOUT_OUT ) ] ),

# 12.2. cusparse<t>gebsr2gebsc_bufferSize()
  func_decl( [ "cusparseSgebsr2gebsc_bufferSize", "cusparseDgebsr2gebsc_bufferSize", "cusparseCgebsr2gebsc_bufferSize", "cusparseZgebsr2gebsc_bufferSize" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('mb', PASSBYVALUE, INOUT_IN ),
               parm_def('nb', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzb', PASSBYVALUE, INOUT_IN ),
               parm_def('bsrSortedVal', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedRowPtr', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedColInd', MEMORY_DEVICE, INOUT_IN ),
               parm_def('rowBlockDim', PASSBYVALUE, INOUT_IN ),
               parm_def('colBlockDim', PASSBYVALUE, INOUT_IN ),
               parm_def('pBufferSizeInBytes', [ MEMORY_HOST, SCALAR ], INOUT_OUT ) ] ),

# 12.3. cusparse<t>gebsr2gebsc()
  func_decl( [ "cusparseSgebsr2gebsc", "cusparseDgebsr2gebsc", "cusparseCgebsr2gebsc", "cusparseZgebsr2gebsc" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('mb', PASSBYVALUE, INOUT_IN ),
               parm_def('nb', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzb', PASSBYVALUE, INOUT_IN ),
               parm_def('bsrSortedVal', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedRowPtr', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedColInd', MEMORY_DEVICE, INOUT_IN ),
               parm_def('rowBlockDim', PASSBYVALUE, INOUT_IN ),
               parm_def('colBlockDim', PASSBYVALUE, INOUT_IN ),
               parm_def('bscVal', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('bscRowInd', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('bscColPtr', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('copyValues', PASSBYVALUE, INOUT_IN ),
               parm_def('baseIdx', PASSBYVALUE, INOUT_IN ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ), ] ),

# 12.4. cusparse<t>gebsr2gebsr_bufferSize()
  func_decl( [ "cusparseSgebsr2gebsr_bufferSize", "cusparseDgebsr2gebsr_bufferSize", "cusparseCgebsr2gebsr_bufferSize", "cusparseZgebsr2gebsr_bufferSize" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('dirA', PASSBYVALUE, INOUT_IN ),
               parm_def('mb', PASSBYVALUE, INOUT_IN ),
               parm_def('nb', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzb', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('bsrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('rowBlockDimA', PASSBYVALUE, INOUT_IN ),
               parm_def('colBlockDimA', PASSBYVALUE, INOUT_IN ),
               parm_def('rowBlockDimC', PASSBYVALUE, INOUT_IN ),
               parm_def('colBlockDimC', PASSBYVALUE, INOUT_IN ),
               parm_def('pBufferSizeInBytes', [ MEMORY_HOST, SCALAR ], INOUT_OUT ) ] ),

# 12.5. cusparse<t>gebsr2gebsr()
  func_decl( [ "cusparseXgebsr2gebsrNnz" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('dirA', PASSBYVALUE, INOUT_IN ),
               parm_def('mb', PASSBYVALUE, INOUT_IN ),
               parm_def('nb', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzb', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('bsrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('rowBlockDimA', PASSBYVALUE, INOUT_IN ),
               parm_def('colBlockDimA', PASSBYVALUE, INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('bsrSortedRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('rowBlockDimC', PASSBYVALUE, INOUT_IN ),
               parm_def('colBlockDimC', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzTotalDevHostPtr', [ MEMORY_HOSTORDEV, SCALAR ], INOUT_OUT ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ) ] ),

  func_decl( [ "cusparseSgebsr2gebsr", "cusparseDgebsr2gebsr", "cusparseCgebsr2gebsr", "cusparseZgebsr2gebsr" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('dirA', PASSBYVALUE, INOUT_IN ),
               parm_def('mb', PASSBYVALUE, INOUT_IN ),
               parm_def('nb', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzb', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('bsrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('rowBlockDimA', PASSBYVALUE, INOUT_IN ),
               parm_def('colBlockDimA', PASSBYVALUE, INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('bsrSortedValC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('bsrSortedRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('bsrSortedColIndC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('rowBlockDimC', PASSBYVALUE, INOUT_IN ),
               parm_def('colBlockDimC', PASSBYVALUE, INOUT_IN ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ) ] ),

# 12.6. cusparse<t>gebsr2csr()
  func_decl( [ "cusparseSgebsr2csr", "cusparseDgebsr2csr", "cusparseCgebsr2csr", "cusparseZgebsr2csr" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('dirA', PASSBYVALUE, INOUT_IN ),
               parm_def('mb', PASSBYVALUE, INOUT_IN ),
               parm_def('nb', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('bsrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('rowBlockDim', PASSBYVALUE, INOUT_IN ),
               parm_def('colBlockDim', PASSBYVALUE, INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrSortedRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrSortedColIndC', MEMORY_DEVICE, INOUT_OUT ) ] ),

# 12.7. cusparse<t>csr2gebsr_bufferSize()
  func_decl( [ "cusparseScsr2gebsr_bufferSize", "cusparseDcsr2gebsr_bufferSize", "cusparseCcsr2gebsr_bufferSize", "cusparseZcsr2gebsr_bufferSize" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('dirA', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('rowBlockDim', PASSBYVALUE, INOUT_IN ),
               parm_def('colBlockDim', PASSBYVALUE, INOUT_IN ),
               parm_def('pBufferSizeInBytes', [ MEMORY_HOST, SCALAR ], INOUT_OUT ) ] ),

# 12.8. cusparse<t>csr2gebsr()
  func_decl( [ "cusparseXcsr2gebsrNnz" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('dirA', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('bsrSortedRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('rowBlockDim', PASSBYVALUE, INOUT_IN ),
               parm_def('colBlockDim', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzTotalDevHostPtr', [ MEMORY_HOSTORDEV, SCALAR ], INOUT_OUT ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ) ] ),

  func_decl( [ "cusparseScsr2gebsr", "cusparseDcsr2gebsr", "cusparseCcsr2gebsr", "cusparseZcsr2gebsr" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('dirA', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('bsrSortedValC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('bsrSortedRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('bsrSortedColIndC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('rowBlockDim', PASSBYVALUE, INOUT_IN ),
               parm_def('colBlockDim', PASSBYVALUE, INOUT_IN ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ) ] ),

# 12.9. cusparse<t>coo2csr()
  func_decl( [ "cusparseXcoo2csr" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('cooRowInd', MEMORY_DEVICE, INOUT_IN ),
               parm_def('nnz', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedRowPtr', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('idxBase', PASSBYVALUE, INOUT_IN ) ] ),

# 12.10. cusparse<t>csc2dense()
  func_decl( [ "cusparseScsc2dense", "cusparseDcsc2dense", "cusparseCcsc2dense", "cusparseZcsc2dense" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('cscSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('cscSortedRowIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('cscSortedColPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('A', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ) ] ),

# 12.11. cusparse<t>csc2hyb()
  func_decl( [ "cusparseScsc2hyb", "cusparseDcsc2hyb", "cusparseCcsc2hyb", "cusparseZcsc2hyb" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('cscSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('cscSortedRowIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('cscSortedColPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('hybA', PASSBYVALUE, INOUT_OUT ),
               parm_def('userEllWidth', PASSBYVALUE, INOUT_IN ),
               parm_def('partitionType', PASSBYVALUE, INOUT_IN ) ] ),

# 12.12. cusparse<t>csr2bsr()
  func_decl( [ "cusparseXcsr2bsrNnz" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('dirA', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('blockDim', PASSBYVALUE, INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('bsrSortedRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('nnzTotalDevHostPtr', [ MEMORY_HOSTORDEV, SCALAR ], INOUT_OUT ) ] ),

  func_decl( [ "cusparseScsr2bsr", "cusparseDcsr2bsr", "cusparseCcsr2bsr", "cusparseZcsr2bsr" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('dirA', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('blockDim', PASSBYVALUE, INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('bsrSortedValC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('bsrSortedRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('bsrSortedColIndC', MEMORY_DEVICE, INOUT_OUT ) ] ),

# 12.13. cusparse<t>csr2coo()
  func_decl( [ "cusparseXcsr2coo" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedRowPtr', MEMORY_DEVICE, INOUT_IN ),
               parm_def('nnz', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('cooRowInd', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('idxBase', PASSBYVALUE, INOUT_IN ) ] ),

# 12.14. cusparse<t>csr2csc()
  func_decl( [ "cusparseScsr2csc", "cusparseDcsr2csc", "cusparseCcsr2csc", "cusparseZcsr2csc" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('nnz', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedVal', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtr', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColInd', MEMORY_DEVICE, INOUT_IN ),
               parm_def('cscSortedVal', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('cscSortedRowInd', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('cscSortedColPtr', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('copyValues', PASSBYVALUE, INOUT_IN ),
               parm_def('idxBase', PASSBYVALUE, INOUT_IN ) ] ),

# 12.15. cusparseCsr2cscEx()
  func_decl( [ "cusparseCsr2cscEx" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('nnz', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedVal', MEMORY_DEVICE, INOUT_IN, { 'typedep' : 'csrSortedValtype' } ),
               parm_def('csrSortedValtype', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedRowPtr', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColInd', MEMORY_DEVICE, INOUT_IN ),
               parm_def('cscSortedVal', MEMORY_DEVICE, INOUT_OUT, { 'typedep' : 'cscSortedValtype' } ),
               parm_def('cscSortedValtype', PASSBYVALUE, INOUT_IN ),
               parm_def('cscSortedRowInd', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('cscSortedColPtr', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('copyValues', PASSBYVALUE, INOUT_IN ),
               parm_def('idxBase', PASSBYVALUE, INOUT_IN ),
               parm_def('executiontype', PASSBYVALUE, INOUT_IN ) ] ),

# 12.16. cusparse<t>csr2dense()
  func_decl( [ "cusparseScsr2dense", "cusparseDcsr2dense", "cusparseCcsr2dense", "cusparseZcsr2dense" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('A', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ) ] ),

# 12.17. cusparse<t>csr2csr_compress()
  func_decl( [ "cusparseScsr2csr_compress", "cusparseDcsr2csr_compress", "cusparseCcsr2csr_compress", "cusparseZcsr2csr_compress" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('descra', PASSBYVALUE, INOUT_IN ),
               parm_def('csrValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('nnzA', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzPerRow', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrValC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrColIndC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('tol', PASSBYVALUE, INOUT_IN ) ] ),

# 12.18. cusparse<t>csr2hyb()
  func_decl( [ "cusparseScsr2hyb", "cusparseDcsr2hyb", "cusparseCcsr2hyb", "cusparseZcsr2hyb" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('hybA', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('userEllWidth', PASSBYVALUE, INOUT_IN ),
               parm_def('partitionType', PASSBYVALUE, INOUT_IN ) ] ),

# 12.19. cusparse<t>dense2csc()
  func_decl( [ "cusparseSdense2csc", "cusparseDdense2csc", "cusparseCdense2csc", "cusparseZdense2csc" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('A', MEMORY_DEVICE, INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzPerCol', MEMORY_DEVICE, INOUT_IN ),
               parm_def('cscSortedValA', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('cscSortedRowIndA', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('cscSortedColPtrA', MEMORY_DEVICE, INOUT_OUT ) ] ),

# 12.20. cusparse<t>dense2csr()
  func_decl( [ "cusparseSdense2csr", "cusparseDdense2csr", "cusparseCdense2csr", "cusparseZdense2csr" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('A', MEMORY_DEVICE, INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzPerRow', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedValA', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_OUT ) ] ),

# 12.21. cusparse<t>dense2hyb()
  func_decl( [ "cusparseSdense2hyb", "cusparseDdense2hyb", "cusparseCdense2hyb", "cusparseZdense2hyb" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('A', MEMORY_DEVICE, INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzPerRow', MEMORY_DEVICE, INOUT_IN ),
               parm_def('hybA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValA', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('userEllWidth', PASSBYVALUE, INOUT_IN ),
               parm_def('partitionType', PASSBYVALUE, INOUT_IN ) ] ),

# 12.22. cusparse<t>hyb2csc()
  func_decl( [ "cusparseShyb2csc", "cusparseDhyb2csc", "cusparseChyb2csc", "cusparseZhyb2csc" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('hybA', PASSBYVALUE, INOUT_IN ),
               parm_def('cscSortedVal', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('cscSortedRowInd', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('cscSortedColPtr', MEMORY_DEVICE, INOUT_OUT ) ] ),

# 12.23. cusparse<t>hyb2csr()
  func_decl( [ "cusparseShyb2csr", "cusparseDhyb2csr", "cusparseChyb2csr", "cusparseZhyb2csr" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('hybA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValA', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_OUT ) ] ),

# 12.24. cusparse<t>hyb2dense()
  func_decl( [ "cusparseShyb2dense", "cusparseDhyb2dense", "cusparseChyb2dense", "cusparseZhyb2dense" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('hybA', PASSBYVALUE, INOUT_IN ),
               parm_def('A', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ) ] ),

# 12.25. cusparse<t>nnz()
  func_decl( [ "cusparseSnnz", "cusparseDnnz", "cusparseCnnz", "cusparseZnnz" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('dirA', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('A', MEMORY_DEVICE, INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzPerRowCol', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('nnzTotalDevHostPtr', [ MEMORY_HOSTORDEV, SCALAR ], INOUT_OUT ) ] ),

# 12.26. cusparseCreateIdentityPermutation()
  func_decl( [ "cusparseCreateIdentityPermutation" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('p', MEMORY_DEVICE, INOUT_OUT ) ] ),

# 12.27. cusparseXcoosort()
  func_decl( [ "cusparseXcoosort_bufferSizeExt" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('nnz', PASSBYVALUE, INOUT_IN ),
               parm_def('cooRowsA', MEMORY_DEVICE, INOUT_INOUT ),
               parm_def('cooColsA', MEMORY_DEVICE, INOUT_INOUT ),
               parm_def('pBufferSizeInBytes', [ MEMORY_HOST, SCALAR ], INOUT_OUT, { "typepatch" : "size_t *" } ) ] ),

  func_decl( [ "cusparseXcoosortByRow", "cusparseXcoosortByColumn" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('nnz', PASSBYVALUE, INOUT_IN ),
               parm_def('cooRowsA', MEMORY_DEVICE, INOUT_INOUT ),
               parm_def('cooColsA', MEMORY_DEVICE, INOUT_INOUT ),
               parm_def('P', MEMORY_DEVICE, INOUT_INOUT ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ) ] ),

# 12.28. cusparseXcsrsort()
  func_decl( [ "cusparseXcsrsort_bufferSizeExt" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('nnz', PASSBYVALUE, INOUT_IN ),
               parm_def('csrRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrColIndA', MEMORY_DEVICE, INOUT_INOUT ),
               parm_def('pBufferSizeInBytes', [ MEMORY_HOST, SCALAR ], INOUT_OUT, { "typepatch" : "size_t *" } ) ] ),

  func_decl( [ "cusparseXcsrsort" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('nnz', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrColIndA', MEMORY_DEVICE, INOUT_INOUT ),
               parm_def('P', MEMORY_DEVICE, INOUT_INOUT ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ) ] ),

# 12.29. cusparseXcscsort()
  func_decl( [ "cusparseXcscsort_bufferSizeExt" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('nnz', PASSBYVALUE, INOUT_IN ),
               parm_def('cscColPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('cscRowIndA', MEMORY_DEVICE, INOUT_INOUT ),
               parm_def('pBufferSizeInBytes', [ MEMORY_HOST, SCALAR ], INOUT_OUT, { "typepatch" : "size_t *" } ) ] ),

  func_decl( [ "cusparseXcscsort" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('nnz', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('cscColPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('cscRowIndA', MEMORY_DEVICE, INOUT_INOUT ),
               parm_def('P', MEMORY_DEVICE, INOUT_INOUT ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ) ] ),

# 12.30. cusparseXcsru2csr()
  func_decl( [ "cusparseCreateCsru2csrInfo" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('info', [ MEMORY_HOST, SCALAR ], INOUT_OUT ) ] ),

  func_decl( [ "cusparseDestroyCsru2csrInfo" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('info', PASSBYVALUE, INOUT_IN ) ] ),

  func_decl( [ "cusparseScsru2csr_bufferSizeExt", "cusparseDcsru2csr_bufferSizeExt", "cusparseCcsru2csr_bufferSizeExt", "cusparseZcsru2csr_bufferSizeExt" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('nnz', PASSBYVALUE, INOUT_IN ),
               parm_def('csrVal', MEMORY_DEVICE, INOUT_INOUT ),
               parm_def('csrRowPtr', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrColInd', MEMORY_DEVICE, INOUT_INOUT ),
               parm_def('info', PASSBYVALUE, INOUT_IN ),
               parm_def('pBufferSizeInBytes', [ MEMORY_HOST, SCALAR ], INOUT_OUT, { "typepatch" : "size_t *" } ) ] ),

  func_decl( [ "cusparseScsru2csr", "cusparseDcsru2csr", "cusparseCcsru2csr", "cusparseZcsru2csr", "cusparseScsr2csru", "cusparseDcsr2csru", "cusparseCcsr2csru", "cusparseZcsr2csru" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('nnz', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrVal', MEMORY_DEVICE, INOUT_INOUT ),
               parm_def('csrRowPtr', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrColInd', MEMORY_DEVICE, INOUT_INOUT ),
               parm_def('info', PASSBYVALUE, INOUT_IN ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ) ] ),

# 12.31. cusparseXpruneDense2csr()
  func_decl( [ "cusparseHpruneDense2csr_bufferSizeExt", "cusparseSpruneDense2csr_bufferSizeExt", "cusparseDpruneDense2csr_bufferSizeExt" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('A', MEMORY_DEVICE, INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('threshold', [ MEMORY_HOSTORDEV, SCALAR ], INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('csrValC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrColIndC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('pBufferSizeInBytes', [ MEMORY_HOST, SCALAR ], INOUT_OUT, { "typepatch" : "size_t *" } ) ] ),

  func_decl( [ "cusparseHpruneDense2csrNnz", "cusparseSpruneDense2csrNnz", "cusparseDpruneDense2csrNnz" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('A', MEMORY_DEVICE, INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('threshold', [ MEMORY_HOSTORDEV, SCALAR ], INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('csrRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('nnzTotalDevHostPtr', [ MEMORY_HOSTORDEV, SCALAR ], INOUT_OUT ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ) ] ),

  func_decl( [ "cusparseHpruneDense2csr", "cusparseSpruneDense2csr", "cusparseDpruneDense2csr" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('A', MEMORY_DEVICE, INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('threshold', [ MEMORY_HOSTORDEV, SCALAR ], INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('csrValC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrColIndC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ) ] ),

# 12.32. cusparseXpruneCsr2csr()
  func_decl( [ "cusparseHpruneCsr2csr_bufferSizeExt", "cusparseSpruneCsr2csr_bufferSizeExt", "cusparseDpruneCsr2csr_bufferSizeExt" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzA', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('threshold', [ MEMORY_HOSTORDEV, SCALAR ], INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('csrValC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrColIndC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('pBufferSizeInBytes', [ MEMORY_HOST, SCALAR ], INOUT_OUT, { "typepatch" : "size_t *" } ) ] ),

  func_decl( [ "cusparseHpruneCsr2csrNnz", "cusparseSpruneCsr2csrNnz", "cusparseDpruneCsr2csrNnz" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzA', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('threshold', [ MEMORY_HOSTORDEV, SCALAR ], INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('csrRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('nnzTotalDevHostPtr', [ MEMORY_HOSTORDEV, SCALAR ], INOUT_OUT ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ) ] ),

  func_decl( [ "cusparseHpruneCsr2csr", "cusparseSpruneCsr2csr", "cusparseDpruneCsr2csr" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzA', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('threshold', [ MEMORY_HOSTORDEV, SCALAR ], INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('csrValC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrColIndC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ) ] ),

# 12.33. cusparseXpruneDense2csrPercentage()
  func_decl( [ "cusparseHpruneDense2csrByPercentage_bufferSizeExt", "cusparseSpruneDense2csrByPercentage_bufferSizeExt", "cusparseDpruneDense2csrByPercentage_bufferSizeExt" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('A', MEMORY_DEVICE, INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('percentage', PASSBYVALUE, INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('csrValC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrColIndC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('info', PASSBYVALUE, INOUT_IN ),
               parm_def('pBufferSizeInBytes', [ MEMORY_HOST, SCALAR ], INOUT_OUT, { "typepatch" : "size_t *" } ) ] ),

  func_decl( [ "cusparseHpruneDense2csrNnzByPercentage", "cusparseSpruneDense2csrNnzByPercentage", "cusparseDpruneDense2csrNnzByPercentage" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('A', MEMORY_DEVICE, INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('percentage', PASSBYVALUE, INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('csrRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('nnzTotalDevHostPtr', [ MEMORY_HOSTORDEV, SCALAR ], INOUT_OUT ),
               parm_def('info', PASSBYVALUE, INOUT_IN ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ) ] ),

  func_decl( [ "cusparseHpruneDense2csrByPercentage", "cusparseSpruneDense2csrByPercentage", "cusparseDpruneDense2csrByPercentage" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('A', MEMORY_DEVICE, INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('percentage', PASSBYVALUE, INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('csrValC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrColIndC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('info', PASSBYVALUE, INOUT_IN ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ) ] ),

# 12.34. cusparseXpruneCsr2csrByPercentage()
  func_decl( [ "cusparseHpruneCsr2csrByPercentage_bufferSizeExt", "cusparseSpruneCsr2csrByPercentage_bufferSizeExt", "cusparseDpruneCsr2csrByPercentage_bufferSizeExt" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzA', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('percentage', PASSBYVALUE, INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('csrValC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrColIndC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('info', PASSBYVALUE, INOUT_IN ),
               parm_def('pBufferSizeInBytes', [ MEMORY_HOST, SCALAR ], INOUT_OUT, { "typepatch" : "size_t *" } ) ] ),

  func_decl( [ "cusparseHpruneCsr2csrNnzByPercentage", "cusparseSpruneCsr2csrNnzByPercentage", "cusparseDpruneCsr2csrNnzByPercentage" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzA', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('percentage', PASSBYVALUE, INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('csrRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('nnzTotalDevHostPtr', [ MEMORY_HOSTORDEV, SCALAR ], INOUT_OUT ),
               parm_def('info', PASSBYVALUE, INOUT_IN ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ) ] ),

  func_decl( [ "cusparseHpruneCsr2csrByPercentage", "cusparseSpruneCsr2csrByPercentage", "cusparseDpruneCsr2csrByPercentage" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzA', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('percentage', PASSBYVALUE, INOUT_IN ),
               parm_def('descrC', PASSBYVALUE, INOUT_IN ),
               parm_def('csrValC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrRowPtrC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('csrColIndC', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('info', PASSBYVALUE, INOUT_IN ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ) ] ),

# 12.35. cusparse<t>nnz_compress()
  func_decl( [ "cusparseSnnz_compress", "cusparseDnnz_compress", "cusparseCnnz_compress", "cusparseZnnz_compress" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('descr', PASSBYVALUE, INOUT_IN ),
               parm_def('csrValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('nnzPerRow', MEMORY_DEVICE, INOUT_IN ),
               parm_def('nnzC', MEMORY_DEVICE, INOUT_IN ),
               parm_def('tol', PASSBYVALUE, INOUT_IN ), ] )
]
