from ...doc import *

# missing: 7.4

cuSPARSE_level2 = [
# 7.1. cusparse<t>bsrmv()
  func_decl( [ "cusparseSbsrmv", "cusparseDbsrmv", "cusparseCbsrmv", "cusparseZbsrmv" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('dirA', PASSBYVALUE, INOUT_IN ),
               parm_def('transA', PASSBYVALUE, INOUT_IN ),
               parm_def('mb', PASSBYVALUE, INOUT_IN ),
               parm_def('nb', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzb', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('bsrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('blockDim', MEMORY_DEVICE, INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n'], INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('y', [ MEMORY_DEVICE, VECTOR, 'm'], INOUT_INOUT ) ] ),

# 7.2. cusparse<t>bsrxmv()
  func_decl( [ "cusparseSbsrxmv", "cusparseDbsrxmv", "cusparseCbsrxmv", "cusparseZbsrxmv" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('dirA', PASSBYVALUE, INOUT_IN ),
               parm_def('transA', PASSBYVALUE, INOUT_IN ),
               parm_def('sizeOfMask', PASSBYVALUE, INOUT_IN ),
               parm_def('mb', PASSBYVALUE, INOUT_IN ),
               parm_def('nb', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzb', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('bsrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedMaskPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedEndPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('blockDim', MEMORY_DEVICE, INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n'], INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('y', [ MEMORY_DEVICE, VECTOR, 'm'], INOUT_INOUT ) ] ),

# 7.3. cusparse<t>csrmv()
  func_decl( [ "cusparseScsrmv", "cusparseDcsrmv", "cusparseCcsrmv", "cusparseZcsrmv" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('transA', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('nnz', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('x', MEMORY_DEVICE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('y', MEMORY_DEVICE, INOUT_OUT ) ] ),

# 7.4. cusparseCsrmvEx()
  func_decl( [ "cusparseCsrmvEx" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('alg', PASSBYVALUE, INOUT_IN ),
               parm_def('transA', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('nnz', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN, { "typedep" : "alphatype" } ),
               parm_def('alphatype', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrValA', PASSBYVALUE, INOUT_IN, { "typedep" : "csrValAtype" } ),
               parm_def('csrValAtype', PASSBYVALUE, INOUT_IN ),
               parm_def('csrRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('x', MEMORY_DEVICE, INOUT_IN, { "typedep" : "xtype" } ),
               parm_def('xtype', PASSBYVALUE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN, { "typedep" : "betatype" } ),
               parm_def('betatype', PASSBYVALUE, INOUT_IN ),
               parm_def('y', PASSBYVALUE, INOUT_OUT, { "typedep" : "ytype" } ),
               parm_def('ytype', PASSBYVALUE, INOUT_IN ),
               parm_def('executiontype', PASSBYVALUE, INOUT_IN ),
               parm_def('buffer', MEMORY_DEVICE, INOUT_IN ) ] ),

## 7.5. cusparseCsrmvEx_bufferSize()
  func_decl( [ "cusparseCsrmvEx_bufferSize" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('alg', PASSBYVALUE, INOUT_IN ),
               parm_def('transA', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('nnz', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN, { "typedep" : "alphatype" } ),
               parm_def('alphatype', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrValA', PASSBYVALUE, INOUT_IN, { "typedep" : "csrValAtype" } ),
               parm_def('csrValAtype', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('x', PASSBYVALUE, INOUT_IN, { "typedep" : "xtype" } ),
               parm_def('xtype', PASSBYVALUE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN, { "typedep" : "betatype" } ),
               parm_def('betatype', PASSBYVALUE, INOUT_IN ),
               parm_def('y', PASSBYVALUE, INOUT_OUT, { "typedep" : "ytype" } ),
               parm_def('ytype', PASSBYVALUE, INOUT_IN ),
               parm_def('executiontype', PASSBYVALUE, INOUT_IN ),
               parm_def('bufferSizeInBytes', [ MEMORY_HOST, SCALAR ], INOUT_OUT, { "typepatch" : "size_t *" } ) ] ),

# 7.6. cusparse<t>csrmv_mp()
  func_decl( [ "cusparseScsrmv_mp", "cusparseDcsrmv_mp", "cusparseCcsrmv_mp", "cusparseZcsrmv_mp" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('transA', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('nnz', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('x', MEMORY_DEVICE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('y', MEMORY_DEVICE, INOUT_OUT ) ] ),

# 7.7. cusparse<t>gemvi()
  func_decl( [ "cusparseSgemvi", "cusparseDgemvi", "cusparseCgemvi", "cusparseZgemvi" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('transA', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('A', MEMORY_DEVICE, INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('nnz', PASSBYVALUE, INOUT_IN ),
               parm_def('xVal', MEMORY_DEVICE, INOUT_IN ),
               parm_def('xInd', MEMORY_DEVICE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('y', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('idxBase', PASSBYVALUE, INOUT_IN ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ) ] ),

# 7.8. cusparse<t>gemvi_bufferSize()
  func_decl( [ "cusparseSgemvi_bufferSize", "cusparseDgemvi_bufferSize", "cusparseCgemvi_bufferSize", "cusparseZgemvi_bufferSize" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('transA', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('nnz', PASSBYVALUE, INOUT_IN ),
               parm_def('pBufferSize', [ MEMORY_HOST, SCALAR ], INOUT_OUT ) ] ),

# 7.9. cusparse<t>bsrsv2_bufferSize()
  func_decl( [ "cusparseSbsrsv2_bufferSize", "cusparseDbsrsv2_bufferSize", "cusparseCbsrsv2_bufferSize", "cusparseZbsrsv2_bufferSize" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('dirA', PASSBYVALUE, INOUT_IN ),
               parm_def('transA', PASSBYVALUE, INOUT_IN ),
               parm_def('mb', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzb', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('bsrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('blockDim', PASSBYVALUE, INOUT_IN ),
               parm_def('info', [ MEMORY_HOST, SCALAR ], INOUT_OUT ),
               parm_def('pBufferSizeInBytes', [ MEMORY_HOST, SCALAR ], INOUT_OUT ) ] ),

# 7.10. cusparse<t>bsrsv2_analysis()
  func_decl( [ "cusparseSbsrsv2_analysis", "cusparseDbsrsv2_analysis", "cusparseCbsrsv2_analysis", "cusparseZbsrsv2_analysis" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('dirA', PASSBYVALUE, INOUT_IN ),
               parm_def('transA', PASSBYVALUE, INOUT_IN ),
               parm_def('mb', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzb', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('bsrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('blockDim', PASSBYVALUE, INOUT_IN ),
               parm_def('info', [ MEMORY_HOST, SCALAR ], INOUT_INOUT ),
               parm_def('policy', PASSBYVALUE, INOUT_IN ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ) ] ),

# 7.11. cusparse<t>bsrsv2_solve()
  func_decl( [ "cusparseSbsrsv2_solve", "cusparseDbsrsv2_solve", "cusparseCbsrsv2_solve", "cusparseZbsrsv2_solve" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('dirA', PASSBYVALUE, INOUT_IN ),
               parm_def('transA', PASSBYVALUE, INOUT_IN ),
               parm_def('mb', PASSBYVALUE, INOUT_IN ),
               parm_def('nnzb', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('bsrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('bsrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('blockDim', PASSBYVALUE, INOUT_IN ),
               parm_def('info', PASSBYVALUE, INOUT_IN ),
               parm_def('f', MEMORY_DEVICE, INOUT_IN ),
               parm_def('x', MEMORY_DEVICE, INOUT_IN ),
               parm_def('policy', PASSBYVALUE, INOUT_IN ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ) ] ),

# 7.12. cusparseXbsrsv2_zeroPivot()
  func_decl( [ "cusparseXbsrsv2_zeroPivot" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('info', PASSBYVALUE, INOUT_IN ),
               parm_def('position', [ MEMORY_HOST, SCALAR ], INOUT_OUT ) ] ),

# 7.13. cusparse<t>csrsv_analysis()
  func_decl( [ "cusparseScsrsv_analysis", "cusparseDcsrsv_analysis", "cusparseCcsrsv_analysis", "cusparseZcsrsv_analysis" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('transA', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('nnz', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('info', [ MEMORY_HOST, SCALAR ], INOUT_INOUT ) ] ),

# 7.14. cusparseCsrsv_analysisEx()
  func_decl( [ "cusparseCsrsv_analysisEx" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('transA', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('nnz', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValA', MEMORY_DEVICE, INOUT_IN, { "typedep" : "csrSortedValAtype" } ),
               parm_def('csrSortedValAtype', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('info', [ MEMORY_HOST, SCALAR ], INOUT_INOUT ),
               parm_def('executiontype', PASSBYVALUE, INOUT_IN ) ] ),

# 7.15. cusparse<t>csrsv_solve()
  func_decl( [ "cusparseScsrsv_solve", "cusparseDcsrsv_solve", "cusparseCcsrsv_solve", "cusparseZcsrsv_solve" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('transA', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('info', [ MEMORY_HOST, SCALAR ], INOUT_IN ),
               parm_def('f', MEMORY_DEVICE, INOUT_IN ),
               parm_def('x', MEMORY_DEVICE, INOUT_OUT ) ] ),

# 7.16. cusparseCsrsv_solveEx()
  func_decl( [ "cusparseCsrsv_solveEx" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('transA', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN, { "typedep" : "alphatype" } ),
               parm_def('alphatype', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValA', MEMORY_DEVICE, INOUT_IN, { "typedep" : "csrSortedValAtype" } ),
               parm_def('csrSortedValAtype', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('info', [ MEMORY_HOST, SCALAR ], INOUT_IN ),
               parm_def('f', MEMORY_DEVICE, INOUT_IN, { "typedep" : "ftype" } ),
               parm_def('ftype', PASSBYVALUE, INOUT_IN ),
               parm_def('x', MEMORY_DEVICE, INOUT_OUT, { "typedep" : "xtype" } ),
               parm_def('xtype', PASSBYVALUE, INOUT_IN ),
               parm_def('executiontype', PASSBYVALUE, INOUT_IN ) ] ),

# 7.17. cusparse<t>csrsv2_bufferSize()
  func_decl( [ "cusparseScsrsv2_bufferSize", "cusparseDcsrsv2_bufferSize", "cusparseCcsrsv2_bufferSize", "cusparseZcsrsv2_bufferSize" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('transA', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('nnz', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('info', [ MEMORY_HOST, SCALAR ], INOUT_OUT ),
               parm_def('pBufferSizeInBytes', [ MEMORY_HOST, SCALAR ], INOUT_OUT ) ] ),

# 7.18. cusparse<t>csrsv2_analysis()
  func_decl( [ "cusparseScsrsv2_analysis", "cusparseDcsrsv2_analysis", "cusparseCcsrsv2_analysis", "cusparseZcsrsv2_analysis" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('transA', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('nnz', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('info', [ MEMORY_HOST, SCALAR ], INOUT_INOUT ),
               parm_def('policy', PASSBYVALUE, INOUT_IN ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ) ] ),

# 7.19. cusparse<t>csrsv2_solve()
  func_decl( [ "cusparseScsrsv2_solve", "cusparseDcsrsv2_solve", "cusparseCcsrsv2_solve", "cusparseZcsrsv2_solve" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('transA', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('nnz', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('csrSortedValA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedRowPtrA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('csrSortedColIndA', MEMORY_DEVICE, INOUT_IN ),
               parm_def('info', [ MEMORY_HOST, SCALAR ], INOUT_IN ),
               parm_def('f', MEMORY_DEVICE, INOUT_IN ),
               parm_def('x', MEMORY_DEVICE, INOUT_OUT ),
               parm_def('policy', PASSBYVALUE, INOUT_IN ),
               parm_def('pBuffer', MEMORY_DEVICE, INOUT_IN ) ] ),

# 7.20. cusparseXcsrsv2_zeroPivot()
  func_decl( [ "cusparseXcsrsv2_zeroPivot" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('info', PASSBYVALUE, INOUT_IN ),
               parm_def('position', [ MEMORY_HOST, SCALAR ], INOUT_OUT ) ] ),

# 7.21. cusparse<t>hybmv()
  func_decl( [ "cusparseShybmv", "cusparseDhybmv", "cusparseChybmv", "cusparseZhybmv" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('transA', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),   # maybe FixMe
               parm_def('hybA', PASSBYVALUE, INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n'], INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('y', [ MEMORY_DEVICE, VECTOR, 'm'], INOUT_INOUT ) ] ),

# 7.22. cusparse<t>hybsv_analysis()
  func_decl( [ "cusparseShybsv_analysis", "cusparseDhybsv_analysis", "cusparseChybsv_analysis", "cusparseZhybsv_analysis" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('transA', PASSBYVALUE, INOUT_IN ),
               parm_def('descrA', PASSBYVALUE, INOUT_IN ),
               parm_def('hybA', PASSBYVALUE, INOUT_IN ),
               parm_def('info', [ MEMORY_HOST, SCALAR ], INOUT_INOUT ) ] ),

# 7.23. cusparse<t>hybsv_solve()
  func_decl( [ "cusparseShybsv_solve", "cusparseDhybsv_solve", "cusparseChybsv_solve", "cusparseZhybsv_solve" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('trans', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUSPARSEPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('descra', PASSBYVALUE, INOUT_IN ),
               parm_def('hybA', PASSBYVALUE, INOUT_IN ),
               parm_def('info', [ MEMORY_HOST, SCALAR ], INOUT_IN ),
               parm_def('f', MEMORY_DEVICE, INOUT_IN ),
               parm_def('x', MEMORY_DEVICE, INOUT_OUT ) ] ),
]
