from ...doc import *

# missing: 2.7.11


cuBLAS_level_3 = [
# 2.7.1. cublas<t>gemm()
# 2.7.2. cublas<t>gemm3m()
  func_decl( [ "cublasSgemm_v2", "cublasDgemm_v2", "cublasCgemm_v2", "cublasZgemm_v2", "cublasHgemm_v2", "cublasCgemm3m_v2", "cublasZgemm3m_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('transa', PASSBYVALUE, INOUT_IN ),
               parm_def('transb', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('k', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('B', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('ldb', PASSBYVALUE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('C', [ MEMORY_DEVICE, VECTOR ], INOUT_INOUT ),
               parm_def('ldc', PASSBYVALUE, INOUT_IN ) ] ),

# 2.7.3. cublas<t>gemmBatched()
  func_decl( [ "cublasHgemmBatched", "cublasSgemmBatched", "cublasDgemmBatched", "cublasCgemmBatched", "cublasZgemmBatched" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('transa', PASSBYVALUE, INOUT_IN ),
               parm_def('transb', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('k', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('Aarray', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('Barray', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('ldb', PASSBYVALUE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('Carray', [ MEMORY_DEVICE, VECTOR ], INOUT_INOUT ),
               parm_def('ldc', PASSBYVALUE, INOUT_IN ),
               parm_def('batchCount', PASSBYVALUE, INOUT_IN ) ] ),

# 2.7.4. cublas<t>gemmStridedBatched()
  func_decl( [ "cublasHgemmStridedBatched", "cublasSgemmStridedBatched", "cublasDgemmStridedBatched", "cublasCgemmStridedBatched", "cublasCgemm3mStridedBatched", "cublasZgemmStridedBatched" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('transa', PASSBYVALUE, INOUT_IN ),
               parm_def('transb', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('k', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('strideA', PASSBYVALUE, INOUT_IN ),
               parm_def('B', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('ldb', PASSBYVALUE, INOUT_IN ),
               parm_def('strideB', PASSBYVALUE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('C', [ MEMORY_DEVICE, VECTOR ], INOUT_INOUT ),
               parm_def('ldc', PASSBYVALUE, INOUT_IN ),
               parm_def('strideC', PASSBYVALUE, INOUT_IN ),
               parm_def('batchCount', PASSBYVALUE, INOUT_IN ) ] ),

# 2.7.5. cublas<t>symm()
  func_decl( [ "cublasSsymm_v2", "cublasDsymm_v2", "cublasCsymm_v2", "cublasZsymm_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('side', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('B', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('ldb', PASSBYVALUE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('C', [ MEMORY_DEVICE, VECTOR ], INOUT_INOUT ),
               parm_def('ldc', PASSBYVALUE, INOUT_IN ) ] ),

# 2.7.6. cublas<t>syrk()
  func_decl( [ "cublasSsyrk_v2", "cublasDsyrk_v2", "cublasCsyrk_v2", "cublasZsyrk_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('trans', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('k', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('C', [ MEMORY_DEVICE, VECTOR ], INOUT_INOUT ),
               parm_def('ldc', PASSBYVALUE, INOUT_IN ) ] ),

# 2.7.7. cublas<t>syr2k()
# 2.7.8. cublas<t>syrkx()
  func_decl( [ "cublasSsyr2k_v2", "cublasDsyr2k_v2", "cublasCsyr2k_v2", "cublasZsyr2k_v2", "cublasSsyrkx", "cublasDsyrkx", "cublasCsyrkx", "cublasZsyrkx" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('trans', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('k', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('B', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('ldb', PASSBYVALUE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('C', [ MEMORY_DEVICE, VECTOR ], INOUT_INOUT ),
               parm_def('ldc', PASSBYVALUE, INOUT_IN ) ] ),

# 2.7.9. cublas<t>trmm()
  func_decl( [ "cublasStrmm_v2", "cublasDtrmm_v2", "cublasCtrmm_v2", "cublasZtrmm_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('side', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('trans', PASSBYVALUE, INOUT_IN ),
               parm_def('diag', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('B', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('ldb', PASSBYVALUE, INOUT_IN ),
               parm_def('C', [ MEMORY_DEVICE, VECTOR ], INOUT_INOUT ),
               parm_def('ldc', PASSBYVALUE, INOUT_IN ) ] ),

# 2.7.10. cublas<t>trsm()
  func_decl( [ "cublasStrsm_v2", "cublasDtrsm_v2", "cublasCtrsm_v2", "cublasZtrsm_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('side', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('trans', PASSBYVALUE, INOUT_IN ),
               parm_def('diag', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('B', [ MEMORY_DEVICE, VECTOR ], INOUT_INOUT ),
               parm_def('ldb', PASSBYVALUE, INOUT_IN ) ] ),

# 2.7.11. cublas<t>trsmBatched()
  func_decl( [ "cublasStrsmBatched", "cublasDtrsmBatched", "cublasCtrsmBatched", "cublasZtrsmBatched" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('side', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('trans', PASSBYVALUE, INOUT_IN ),
               parm_def('diag', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('B', [ MEMORY_DEVICE, VECTOR ], INOUT_INOUT ),
               parm_def('ldb', PASSBYVALUE, INOUT_IN ),
               parm_def('batchCount', PASSBYVALUE, INOUT_IN ) ] ),

# 2.7.12. cublas<t>hemm()
  func_decl( [ "cublasChemm_v2", "cublasZhemm_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('side', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('B', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('ldb', PASSBYVALUE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ), # FixMe
               parm_def('C', [ MEMORY_DEVICE, VECTOR ], INOUT_INOUT ),
               parm_def('ldc', PASSBYVALUE, INOUT_IN ) ] ),

# 2.7.13. cublas<t>herk()
  func_decl( [ "cublasCherk_v2", "cublasZherk_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('trans', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('k', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ), # FixMe
               parm_def('C', [ MEMORY_DEVICE, VECTOR ], INOUT_INOUT ),
               parm_def('ldc', PASSBYVALUE, INOUT_IN ) ] ),

# 2.7.14. cublas<t>her2k()
# 2.7.15. cublas<t>herkx()
  func_decl( [ "cublasCher2k_v2", "cublasZher2k_v2", "cublasCherkx", "cublasZherkx" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('trans', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('k', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('B', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('ldb', PASSBYVALUE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('C', [ MEMORY_DEVICE, VECTOR ], INOUT_INOUT ),
               parm_def('ldc', PASSBYVALUE, INOUT_IN ) ] )
]
