from ...doc import *

cuBLAS_level_2 = [
# 2.6.1. cublas<t>gbmv()
  func_decl( [ "cublasSgbmv_v2", "cublasDgbmv_v2", "cublasCgbmv_v2", "cublasZgbmv_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('trans', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('kl', PASSBYVALUE, INOUT_IN ),
               parm_def('ku', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n', 'incx'], INOUT_IN ),
               parm_def('incx', PASSBYVALUE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('y', [ MEMORY_DEVICE, VECTOR, 'n', 'incy'], INOUT_INOUT ),
               parm_def('incy', PASSBYVALUE, INOUT_IN ) ] ),

# 2.6.2. cublas<t>gemv()
  func_decl( [ "cublasSgemv_v2", "cublasDgemv_v2", "cublasCgemv_v2", "cublasZgemv_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('trans', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n', 'incx'], INOUT_IN ),
               parm_def('incx', PASSBYVALUE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('y', [ MEMORY_DEVICE, VECTOR, 'n', 'incy'], INOUT_INOUT ),
               parm_def('incy', PASSBYVALUE, INOUT_IN ) ] ),

# 2.6.3. cublas<t>ger()
  func_decl( [ "cublasSger_v2", "cublasDger_v2", "cublasCgeru_v2", "cublasCgerc_v2", "cublasZgeru_v2", "cublasZgerc_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('m', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n', 'incx'], INOUT_IN ),
               parm_def('incx', PASSBYVALUE, INOUT_IN ),
               parm_def('y', [ MEMORY_DEVICE, VECTOR, 'n', 'incy'], INOUT_IN ),
               parm_def('incy', PASSBYVALUE, INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_INOUT ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ) ] ),

# 2.6.4. cublas<t>sbmv()
  func_decl( [ "cublasSsbmv_v2", "cublasDsbmv_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('k', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n', 'incx'], INOUT_IN ),
               parm_def('incx', PASSBYVALUE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('y', [ MEMORY_DEVICE, VECTOR, 'n', 'incy'], INOUT_INOUT ),
               parm_def('incy', PASSBYVALUE, INOUT_IN ) ] ),

# 2.6.5. cublas<t>spmv()
  func_decl( [ "cublasSspmv_v2", "cublasDspmv_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('AP', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n', 'incx'], INOUT_IN ),
               parm_def('incx', PASSBYVALUE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('y', [ MEMORY_DEVICE, VECTOR, 'n', 'incy'], INOUT_IN ),
               parm_def('incy', PASSBYVALUE, INOUT_IN ) ] ),

# 2.6.6. cublas<t>spr()
  func_decl( [ "cublasSspr_v2", "cublasDspr_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n', 'incx'], INOUT_IN ),
               parm_def('incx', PASSBYVALUE, INOUT_IN ),
               parm_def('AP', [ MEMORY_DEVICE, VECTOR ], INOUT_INOUT ) ] ),

# 2.6.7. cublas<t>spr2()
  func_decl( [ "cublasSspr2_v2", "cublasDspr2_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n', 'incx'], INOUT_IN ),
               parm_def('incx', PASSBYVALUE, INOUT_IN ),
               parm_def('y', [ MEMORY_DEVICE, VECTOR, 'n', 'incy'], INOUT_IN ),
               parm_def('incy', PASSBYVALUE, INOUT_IN ),
               parm_def('AP', [ MEMORY_DEVICE, VECTOR ], INOUT_INOUT ) ] ),

# 2.6.8. cublas<t>symv()
  func_decl( [ "cublasSsymv_v2", "cublasDsymv_v2", "cublasCsymv_v2", "cublasZsymv_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n', 'incx'], INOUT_IN ),
               parm_def('incx', PASSBYVALUE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('y', [ MEMORY_DEVICE, VECTOR, 'n', 'incy'], INOUT_INOUT ),
               parm_def('incy', PASSBYVALUE, INOUT_IN ) ] ),

# 2.6.9. cublas<t>syr()
  func_decl( [ "cublasSsyr_v2", "cublasDsyr_v2", "cublasCsyr_v2", "cublasZsyr_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n', 'incx'], INOUT_IN ),
               parm_def('incx', PASSBYVALUE, INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_INOUT ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ) ] ),

# 2.6.10. cublas<t>syr2()
  func_decl( [ "cublasSsyr2_v2", "cublasDsyr2_v2", "cublasCsyr2_v2", "cublasZsyr2_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n', 'incx'], INOUT_IN ),
               parm_def('incx', PASSBYVALUE, INOUT_IN ),
               parm_def('y', [ MEMORY_DEVICE, VECTOR, 'n', 'incy'], INOUT_IN ),
               parm_def('incy', PASSBYVALUE, INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_INOUT ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ) ] ),

# 2.6.11. cublas<t>tbmv()
  func_decl( [ "cublasStbmv_v2", "cublasDtbmv_v2", "cublasCtbmv_v2", "cublasZtbmv_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('trans', PASSBYVALUE, INOUT_IN ),
               parm_def('diag', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('k', PASSBYVALUE, INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n', 'incx'], INOUT_INOUT ),
               parm_def('incx', PASSBYVALUE, INOUT_IN ) ] ),

# 2.6.12. cublas<t>tbsv()
  func_decl( [ "cublasStbsv_v2", "cublasDtbsv_v2", "cublasCtbsv_v2", "cublasZtbsv_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('trans', PASSBYVALUE, INOUT_IN ),
               parm_def('diag', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('k', PASSBYVALUE, INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n', 'incx'], INOUT_INOUT ),
               parm_def('incx', PASSBYVALUE, INOUT_IN ) ] ),

# 2.6.13. cublas<t>tpmv()
  func_decl( [ "cublasStpmv_v2", "cublasDtpmv_v2", "cublasCtpmv_v2", "cublasZtpmv_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('trans', PASSBYVALUE, INOUT_IN ),
               parm_def('diag', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('AP', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n', 'incx'], INOUT_INOUT ),
               parm_def('incx', PASSBYVALUE, INOUT_IN ) ] ),

# 2.6.14. cublas<t>tpsv()
  func_decl( [ "cublasStpsv_v2", "cublasDtpsv_v2", "cublasCtpsv_v2", "cublasZtpsv_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('trans', PASSBYVALUE, INOUT_IN ),
               parm_def('diag', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('AP', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n', 'incx'], INOUT_INOUT ),
               parm_def('incx', PASSBYVALUE, INOUT_IN ) ] ),

# 2.6.15. cublas<t>trmv()
  func_decl( [ "cublasStrmv_v2", "cublasDtrmv_v2", "cublasCtrmv_v2", "cublasZtrmv_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('trans', PASSBYVALUE, INOUT_IN ),
               parm_def('diag', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n', 'incx'], INOUT_INOUT ),
               parm_def('incx', PASSBYVALUE, INOUT_IN ) ] ),

# 2.6.16. cublas<t>trsv()
  func_decl( [ "cublasStrsv_v2", "cublasDtrsv_v2", "cublasCtrsv_v2", "cublasZtrsv_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('trans', PASSBYVALUE, INOUT_IN ),
               parm_def('diag', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n', 'incx'], INOUT_INOUT ),
               parm_def('incx', PASSBYVALUE, INOUT_IN ) ] ),

# 2.6.17. cublas<t>hemv()
  func_decl( [ "cublasChemv_v2", "cublasZhemv_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n', 'incx'], INOUT_IN ),
               parm_def('incx', PASSBYVALUE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('y', [ MEMORY_DEVICE, VECTOR, 'n', 'incy'], INOUT_INOUT ),
               parm_def('incy', PASSBYVALUE, INOUT_IN ) ] ),

# 2.6.18. cublas<t>hbmv()
  func_decl( [ "cublasChbmv_v2", "cublasZhbmv_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('k', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n', 'incx'], INOUT_IN ),
               parm_def('incx', PASSBYVALUE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('y', [ MEMORY_DEVICE, VECTOR, 'n', 'incy'], INOUT_INOUT ),
               parm_def('incy', PASSBYVALUE, INOUT_IN ) ] ),

# 2.6.19. cublas<t>hpmv()
  func_decl( [ "cublasChpmv_v2", "cublasZhpmv_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('AP', [ MEMORY_DEVICE, VECTOR ], INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n', 'incx'], INOUT_IN ),
               parm_def('incx', PASSBYVALUE, INOUT_IN ),
               parm_def('beta', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('y', [ MEMORY_DEVICE, VECTOR, 'n', 'incy'], INOUT_INOUT ),
               parm_def('incy', PASSBYVALUE, INOUT_IN ) ] ),

# 2.6.20. cublas<t>her()
  func_decl( [ "cublasCher_v2", "cublasZher_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n', 'incx'], INOUT_IN ),
               parm_def('incx', PASSBYVALUE, INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_INOUT ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ) ] ),

# 2.6.21. cublas<t>her2()
  func_decl( [ "cublasCher2_v2", "cublasZher2_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n', 'incx'], INOUT_IN ),
               parm_def('incx', PASSBYVALUE, INOUT_IN ),
               parm_def('y', [ MEMORY_DEVICE, VECTOR, 'n', 'incy'], INOUT_IN ),
               parm_def('incy', PASSBYVALUE, INOUT_IN ),
               parm_def('A', [ MEMORY_DEVICE, VECTOR ], INOUT_INOUT ),
               parm_def('lda', PASSBYVALUE, INOUT_IN ) ] ),

# 2.6.22. cublas<t>hpr()
  func_decl( [ "cublasChpr_v2", "cublasZhpr_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n', 'incx'], INOUT_IN ),
               parm_def('incx', PASSBYVALUE, INOUT_IN ),
               parm_def('AP', [ MEMORY_DEVICE, VECTOR ], INOUT_INOUT ) ] ),

# 2.6.23. cublas<t>hpr2()
  func_decl( [ "cublasChpr2_v2", "cublasZhpr2_v2" ],
             [ parm_def('handle', PASSBYVALUE, INOUT_IN ),
               parm_def('uplo', PASSBYVALUE, INOUT_IN ),
               parm_def('n', PASSBYVALUE, INOUT_IN ),
               parm_def('alpha', [ MEMORY_HoD_CUBLASPOINTERMODE, SCALAR ], INOUT_IN ),
               parm_def('x', [ MEMORY_DEVICE, VECTOR, 'n', 'incx'], INOUT_IN ),
               parm_def('incx', PASSBYVALUE, INOUT_IN ),
               parm_def('y', [ MEMORY_DEVICE, VECTOR, 'n', 'incy'], INOUT_IN ),
               parm_def('incy', PASSBYVALUE, INOUT_IN ),
               parm_def('AP', [ MEMORY_DEVICE, VECTOR ], INOUT_INOUT ) ] )
]
