#include "hfcuda_common.c"

#include "modules/hfcuda_comm.c"
#include "modules/hfcuda_functions.h"
#include "modules/hfcuda_shlib.c"

#include "wrappers/io/daemon.c"
#include "wrappers/driver_daemon.c"

#include "wrappers/cudart/daemon/device.c"
#include "wrappers/cudart/daemon/execution.c"
#include "wrappers/cudart/daemon/memory.c"
#include "wrappers/cudart/daemon/profiler.c"

#include "wrappers/cuda_driverapi/daemon/unified_addressing.c"

#include "wrappers/daemon_fnc_auto.c"

typedef struct {
    hfcomm_t   conn;
    pthread_t  thread;
} args_t;

hfcomm_t server;

hferr_t hf_handle(hfcuda_function_t function)
{
    hfdeb("HANDLE: %d\n", function);
    clockme("(D) hf_handle");

    switch (function) {

        // io
        // ----------------------------------------
        case HFCUDA_IO_hf_gpu_fopen:
          return handle_HFCUDA_IO_hf_gpu_fopen();
        case HFCUDA_IO_hf_gpu_fwrite:
          return handle_HFCUDA_IO_hf_gpu_fwrite();
        case HFCUDA_IO_hf_gpu_fread:
          return handle_HFCUDA_IO_hf_gpu_fread();
        case HFCUDA_IO_hf_gpu_fclose:
          return handle_HFCUDA_IO_hf_gpu_fclose();
        case HFCUDA_IO_fopen:
          return handle_HFCUDA_IO_fopen();
        case HFCUDA_IO_fwrite:
          return handle_HFCUDA_IO_fwrite();
        case HFCUDA_CUDART_cudaMemPrefetchAsync:
          return handle_HFCUDA_CUDART_cudaMemPrefetchAsync();

        // cuda_driver
        // ----------------------------------------
        case HFCUDA_CUDA_cuDeviceGetAttribute: return handle_HFCUDA_CUDA_cuDeviceGetAttribute();
        case HFCUDA_CUDA_cuDeviceTotalMem:     return handle_HFCUDA_CUDA_cuDeviceTotalMem();
        case HFCUDA_CUDA_cuMemAlloc:           return handle_HFCUDA_CUDA_cuMemAlloc();
        case HFCUDA_CUDA_cuMemHostAlloc:       return handle_HFCUDA_CUDA_cuMemHostAlloc();
        case HFCUDA_CUDA_cuMemFree:            return handle_HFCUDA_CUDA_cuMemFree();
        case HFCUDA_CUDA_cuMemFreeHost:        return handle_HFCUDA_CUDA_cuMemFreeHost();
        case HFCUDA_CUDA_cuMemAllocHost:       return handle_HFCUDA_CUDA_cuMemAllocHost();
        case HFCUDA_CUDA_cuMemcpyHtoDAsync:    return handle_HFCUDA_CUDA_cuMemcpyHtoDAsync();
        case HFCUDA_CUDA_cuDeviceGetName:      return handle_HFCUDA_CUDA_cuDeviceGetName();
        case HFCUDA_CUDA_cuMemcpyDtoHAsync:    return handle_HFCUDA_CUDA_cuMemcpyDtoHAsync();
        case HFCUDA_CUDA_cuModuleLoadDataEx:   return handle_HFCUDA_CUDA_cuModuleLoadDataEx();
        case HFCUDA_CUDA_cuMemGetInfo:         return handle_HFCUDA_CUDA_cuMemGetInfo();
        case HFCUDA_CUDA_cuMemcpyHtoD:         return handle_HFCUDA_CUDA_cuMemcpyHtoD();
        case HFCUDA_CUDA_cuMemcpyDtoH:         return handle_HFCUDA_CUDA_cuMemcpyDtoH();
        case HFCUDA_CUDA_cuTexRefSetAddress:   return handle_HFCUDA_CUDA_cuTexRefSetAddress();
        case HFCUDA_CUDA_cuModuleGetFunction:  return handle_HFCUDA_CUDA_cuModuleGetFunction();
        case HFCUDA_CUDA_cuTexRefSetFormat:    return handle_HFCUDA_CUDA_cuTexRefSetFormat();
        case HFCUDA_CUDA_cuDeviceGetCount:     return handle_HFCUDA_CUDA_cuDeviceGetCount();
        case HFCUDA_CUDA_cuInit:               return handle_HFCUDA_CUDA_cuInit();
        case HFCUDA_CUDA_cuModuleGetTexRef:    return handle_HFCUDA_CUDA_cuModuleGetTexRef();
        case HFCUDA_CUDA_cuDeviceGet:          return handle_HFCUDA_CUDA_cuDeviceGet();
        case HFCUDA_CUDA_cuLaunchKernel:       return handle_HFCUDA_CUDA_cuLaunchKernel();

        // cudart/device
        // ----------------------------------------
        case HFCUDA_CUDART_cudaGetDeviceProperties:
            return handle_HFCUDA_CUDART_cudaGetDeviceProperties();
        case HFCUDA_CUDART_cudaSetDevice:
            return handle_HFCUDA_CUDART_cudaSetDevice();

        // cudart/memory
        // ----------------------------------------
        case HFCUDA_CUDART_cudaFree:
            return handle_HFCUDA_CUDART_cudaFree();
        case HFCUDA_CUDART_cudaHostRegister:
            return handle_HFCUDA_CUDART_cudaHostRegister();
        case HFCUDA_CUDART_cudaMalloc:
            return handle_HFCUDA_CUDART_cudaMalloc();
        case HFCUDA_CUDART_cudaMallocHost:
            return handle_HFCUDA_CUDART_cudaMallocHost();
        case HFCUDA_CUDART_cudaMemGetInfo:
            return handle_HFCUDA_CUDART_cudaMemGetInfo();
        case HFCUDA_CUDART_cudaMemcpy:
            return handle_HFCUDA_CUDART_cudaMemcpy();
        case HFCUDA_CUDART_cudaMemcpyAsync:
            return handle_HFCUDA_CUDART_cudaMemcpyAsync();
        case HFCUDA_CUDART_cudaMemcpyToSymbol:
            return handle_HFCUDA_CUDART_cudaMemcpyToSymbol();
        case HFCUDA_CUDART_cudaHostAlloc:
            return handle_HFCUDA_CUDART_cudaHostAlloc();


        // cudart/execution
        // ----------------------------------------
        case HFCUDA_CUDART_cudaConfigureCall:
            return handle_HFCUDA_CUDART_cudaConfigureCall();
        case HFCUDA_CUDART_cudaLaunch:
            return handle_HFCUDA_CUDART_cudaLaunch();
        case HFCUDA_CUDART_cudaSetupArgument:
            return handle_HFCUDA_CUDART_cudaSetupArgument();

        case HFCUDA_CUDART_cudaLaunchKernel:
            return handle_HFCUDA_CUDART_cudaLaunchKernel();


        // cudart/profiler
        // ----------------------------------------
        case HFCUDA_CUDART_cudaProfilerStart:
            return handle_HFCUDA_CUDART_cudaProfilerStart();
        case HFCUDA_CUDART_cudaProfilerStop:
            return handle_HFCUDA_CUDART_cudaProfilerStop();

           
        // cuda/unified adressing
        // ----------------------------------------
        case HFCUDA_CUDA_cuPointerGetAttributes:
            return handle_HFCUDA_CUDA_cuPointerGetAttributes();


    /* !!! vvv AUTO GENERATED vvv !!! */
        case HFCUDA_cuCtxAttach:
            return handle_HFCUDA_cuCtxAttach();
        case HFCUDA_cuCtxCreate_v2:
            return handle_HFCUDA_cuCtxCreate_v2();
        case HFCUDA_cuCtxDestroy_v2:
            return handle_HFCUDA_cuCtxDestroy_v2();
        case HFCUDA_cuCtxDetach:
            return handle_HFCUDA_cuCtxDetach();
        case HFCUDA_cuCtxGetApiVersion:
            return handle_HFCUDA_cuCtxGetApiVersion();
        case HFCUDA_cuCtxGetCacheConfig:
            return handle_HFCUDA_cuCtxGetCacheConfig();
        case HFCUDA_cuCtxGetCurrent:
            return handle_HFCUDA_cuCtxGetCurrent();
        case HFCUDA_cuCtxGetDevice:
            return handle_HFCUDA_cuCtxGetDevice();
        case HFCUDA_cuCtxGetFlags:
            return handle_HFCUDA_cuCtxGetFlags();
        case HFCUDA_cuCtxGetLimit:
            return handle_HFCUDA_cuCtxGetLimit();
        case HFCUDA_cuCtxGetSharedMemConfig:
            return handle_HFCUDA_cuCtxGetSharedMemConfig();
        case HFCUDA_cuCtxGetStreamPriorityRange:
            return handle_HFCUDA_cuCtxGetStreamPriorityRange();
        case HFCUDA_cuCtxSetCacheConfig:
            return handle_HFCUDA_cuCtxSetCacheConfig();
        case HFCUDA_cuCtxSetCurrent:
            return handle_HFCUDA_cuCtxSetCurrent();
        case HFCUDA_cuCtxSetLimit:
            return handle_HFCUDA_cuCtxSetLimit();
        case HFCUDA_cuCtxSetSharedMemConfig:
            return handle_HFCUDA_cuCtxSetSharedMemConfig();
        case HFCUDA_cuCtxSynchronize:
            return handle_HFCUDA_cuCtxSynchronize();
        case HFCUDA_cuDeviceComputeCapability:
            return handle_HFCUDA_cuDeviceComputeCapability();
        case HFCUDA_cuDeviceGetProperties:
            return handle_HFCUDA_cuDeviceGetProperties();
        case HFCUDA_cuDevicePrimaryCtxGetState:
            return handle_HFCUDA_cuDevicePrimaryCtxGetState();
        case HFCUDA_cuDevicePrimaryCtxRelease:
            return handle_HFCUDA_cuDevicePrimaryCtxRelease();
        case HFCUDA_cuDevicePrimaryCtxReset:
            return handle_HFCUDA_cuDevicePrimaryCtxReset();
        case HFCUDA_cuDevicePrimaryCtxRetain:
            return handle_HFCUDA_cuDevicePrimaryCtxRetain();
        case HFCUDA_cuDevicePrimaryCtxSetFlags:
            return handle_HFCUDA_cuDevicePrimaryCtxSetFlags();
        case HFCUDA_cuDriverGetVersion:
            return handle_HFCUDA_cuDriverGetVersion();
        case HFCUDA_cuEventCreate:
            return handle_HFCUDA_cuEventCreate();
        case HFCUDA_cuEventDestroy_v2:
            return handle_HFCUDA_cuEventDestroy_v2();
        case HFCUDA_cuEventElapsedTime:
            return handle_HFCUDA_cuEventElapsedTime();
        case HFCUDA_cuEventQuery:
            return handle_HFCUDA_cuEventQuery();
        case HFCUDA_cuEventRecord:
            return handle_HFCUDA_cuEventRecord();
        case HFCUDA_cuEventSynchronize:
            return handle_HFCUDA_cuEventSynchronize();
        case HFCUDA_cuFuncGetAttribute:
            return handle_HFCUDA_cuFuncGetAttribute();
        case HFCUDA_cuFuncSetAttribute:
            return handle_HFCUDA_cuFuncSetAttribute();
        case HFCUDA_cuFuncSetBlockShape:
            return handle_HFCUDA_cuFuncSetBlockShape();
        case HFCUDA_cuFuncSetCacheConfig:
            return handle_HFCUDA_cuFuncSetCacheConfig();
        case HFCUDA_cuFuncSetSharedMemConfig:
            return handle_HFCUDA_cuFuncSetSharedMemConfig();
        case HFCUDA_cuFuncSetSharedSize:
            return handle_HFCUDA_cuFuncSetSharedSize();
        case HFCUDA_cuLaunch:
            return handle_HFCUDA_cuLaunch();
        case HFCUDA_cuLaunchGrid:
            return handle_HFCUDA_cuLaunchGrid();
        case HFCUDA_cuLaunchGridAsync:
            return handle_HFCUDA_cuLaunchGridAsync();
        case HFCUDA_cuParamSetSize:
            return handle_HFCUDA_cuParamSetSize();
        case HFCUDA_cuParamSetTexRef:
            return handle_HFCUDA_cuParamSetTexRef();
        case HFCUDA_cuParamSetf:
            return handle_HFCUDA_cuParamSetf();
        case HFCUDA_cuParamSeti:
            return handle_HFCUDA_cuParamSeti();
        case HFCUDA_cuStreamAttachMemAsync:
            return handle_HFCUDA_cuStreamAttachMemAsync();
        case HFCUDA_cuStreamCreate:
            return handle_HFCUDA_cuStreamCreate();
        case HFCUDA_cuStreamCreateWithPriority:
            return handle_HFCUDA_cuStreamCreateWithPriority();
        case HFCUDA_cuStreamDestroy_v2:
            return handle_HFCUDA_cuStreamDestroy_v2();
        case HFCUDA_cuStreamGetFlags:
            return handle_HFCUDA_cuStreamGetFlags();
        case HFCUDA_cuStreamGetPriority:
            return handle_HFCUDA_cuStreamGetPriority();
        case HFCUDA_cuStreamQuery:
            return handle_HFCUDA_cuStreamQuery();
        case HFCUDA_cuStreamSynchronize:
            return handle_HFCUDA_cuStreamSynchronize();
        case HFCUDA_cuStreamWaitEvent:
            return handle_HFCUDA_cuStreamWaitEvent();
        case HFCUDA_cuStreamWaitValue32:
            return handle_HFCUDA_cuStreamWaitValue32();
        case HFCUDA_cuStreamWaitValue64:
            return handle_HFCUDA_cuStreamWaitValue64();
        case HFCUDA_cuStreamWriteValue32:
            return handle_HFCUDA_cuStreamWriteValue32();
        case HFCUDA_cuStreamWriteValue64:
            return handle_HFCUDA_cuStreamWriteValue64();
        case HFCUDA_cublasAxpyEx:
            return handle_HFCUDA_cublasAxpyEx();
        case HFCUDA_cublasCaxpy_v2:
            return handle_HFCUDA_cublasCaxpy_v2();
        case HFCUDA_cublasCcopy_v2:
            return handle_HFCUDA_cublasCcopy_v2();
        case HFCUDA_cublasCdgmm:
            return handle_HFCUDA_cublasCdgmm();
        case HFCUDA_cublasCdotc_v2:
            return handle_HFCUDA_cublasCdotc_v2();
        case HFCUDA_cublasCdotu_v2:
            return handle_HFCUDA_cublasCdotu_v2();
        case HFCUDA_cublasCgbmv_v2:
            return handle_HFCUDA_cublasCgbmv_v2();
        case HFCUDA_cublasCgeam:
            return handle_HFCUDA_cublasCgeam();
        case HFCUDA_cublasCgelsBatched:
            return handle_HFCUDA_cublasCgelsBatched();
        case HFCUDA_cublasCgemm3mStridedBatched:
            return handle_HFCUDA_cublasCgemm3mStridedBatched();
        case HFCUDA_cublasCgemmBatched:
            return handle_HFCUDA_cublasCgemmBatched();
        case HFCUDA_cublasCgemmEx:
            return handle_HFCUDA_cublasCgemmEx();
        case HFCUDA_cublasCgemmStridedBatched:
            return handle_HFCUDA_cublasCgemmStridedBatched();
        case HFCUDA_cublasCgemm_v2:
            return handle_HFCUDA_cublasCgemm_v2();
        case HFCUDA_cublasCgemv_v2:
            return handle_HFCUDA_cublasCgemv_v2();
        case HFCUDA_cublasCgeqrfBatched:
            return handle_HFCUDA_cublasCgeqrfBatched();
        case HFCUDA_cublasCgerc_v2:
            return handle_HFCUDA_cublasCgerc_v2();
        case HFCUDA_cublasCgeru_v2:
            return handle_HFCUDA_cublasCgeru_v2();
        case HFCUDA_cublasCgetrfBatched:
            return handle_HFCUDA_cublasCgetrfBatched();
        case HFCUDA_cublasCgetriBatched:
            return handle_HFCUDA_cublasCgetriBatched();
        case HFCUDA_cublasCgetrsBatched:
            return handle_HFCUDA_cublasCgetrsBatched();
        case HFCUDA_cublasChbmv_v2:
            return handle_HFCUDA_cublasChbmv_v2();
        case HFCUDA_cublasChemm_v2:
            return handle_HFCUDA_cublasChemm_v2();
        case HFCUDA_cublasChemv_v2:
            return handle_HFCUDA_cublasChemv_v2();
        case HFCUDA_cublasCher2_v2:
            return handle_HFCUDA_cublasCher2_v2();
        case HFCUDA_cublasCher2k_v2:
            return handle_HFCUDA_cublasCher2k_v2();
        case HFCUDA_cublasCher_v2:
            return handle_HFCUDA_cublasCher_v2();
        case HFCUDA_cublasCherk3mEx:
            return handle_HFCUDA_cublasCherk3mEx();
        case HFCUDA_cublasCherkEx:
            return handle_HFCUDA_cublasCherkEx();
        case HFCUDA_cublasCherk_v2:
            return handle_HFCUDA_cublasCherk_v2();
        case HFCUDA_cublasCherkx:
            return handle_HFCUDA_cublasCherkx();
        case HFCUDA_cublasChpmv_v2:
            return handle_HFCUDA_cublasChpmv_v2();
        case HFCUDA_cublasChpr2_v2:
            return handle_HFCUDA_cublasChpr2_v2();
        case HFCUDA_cublasChpr_v2:
            return handle_HFCUDA_cublasChpr_v2();
        case HFCUDA_cublasCmatinvBatched:
            return handle_HFCUDA_cublasCmatinvBatched();
        case HFCUDA_cublasCreate_v2:
            return handle_HFCUDA_cublasCreate_v2();
        case HFCUDA_cublasCrot_v2:
            return handle_HFCUDA_cublasCrot_v2();
        case HFCUDA_cublasCrotg_v2:
            return handle_HFCUDA_cublasCrotg_v2();
        case HFCUDA_cublasCscal_v2:
            return handle_HFCUDA_cublasCscal_v2();
        case HFCUDA_cublasCsrot_v2:
            return handle_HFCUDA_cublasCsrot_v2();
        case HFCUDA_cublasCsscal_v2:
            return handle_HFCUDA_cublasCsscal_v2();
        case HFCUDA_cublasCswap_v2:
            return handle_HFCUDA_cublasCswap_v2();
        case HFCUDA_cublasCsymm_v2:
            return handle_HFCUDA_cublasCsymm_v2();
        case HFCUDA_cublasCsymv_v2:
            return handle_HFCUDA_cublasCsymv_v2();
        case HFCUDA_cublasCsyr2_v2:
            return handle_HFCUDA_cublasCsyr2_v2();
        case HFCUDA_cublasCsyr2k_v2:
            return handle_HFCUDA_cublasCsyr2k_v2();
        case HFCUDA_cublasCsyr_v2:
            return handle_HFCUDA_cublasCsyr_v2();
        case HFCUDA_cublasCsyrk3mEx:
            return handle_HFCUDA_cublasCsyrk3mEx();
        case HFCUDA_cublasCsyrkEx:
            return handle_HFCUDA_cublasCsyrkEx();
        case HFCUDA_cublasCsyrk_v2:
            return handle_HFCUDA_cublasCsyrk_v2();
        case HFCUDA_cublasCsyrkx:
            return handle_HFCUDA_cublasCsyrkx();
        case HFCUDA_cublasCtbmv_v2:
            return handle_HFCUDA_cublasCtbmv_v2();
        case HFCUDA_cublasCtbsv_v2:
            return handle_HFCUDA_cublasCtbsv_v2();
        case HFCUDA_cublasCtpmv_v2:
            return handle_HFCUDA_cublasCtpmv_v2();
        case HFCUDA_cublasCtpsv_v2:
            return handle_HFCUDA_cublasCtpsv_v2();
        case HFCUDA_cublasCtpttr:
            return handle_HFCUDA_cublasCtpttr();
        case HFCUDA_cublasCtrmm_v2:
            return handle_HFCUDA_cublasCtrmm_v2();
        case HFCUDA_cublasCtrmv_v2:
            return handle_HFCUDA_cublasCtrmv_v2();
        case HFCUDA_cublasCtrsmBatched:
            return handle_HFCUDA_cublasCtrsmBatched();
        case HFCUDA_cublasCtrsm_v2:
            return handle_HFCUDA_cublasCtrsm_v2();
        case HFCUDA_cublasCtrsv_v2:
            return handle_HFCUDA_cublasCtrsv_v2();
        case HFCUDA_cublasCtrttp:
            return handle_HFCUDA_cublasCtrttp();
        case HFCUDA_cublasDasum_v2:
            return handle_HFCUDA_cublasDasum_v2();
        case HFCUDA_cublasDaxpy_v2:
            return handle_HFCUDA_cublasDaxpy_v2();
        case HFCUDA_cublasDcopy_v2:
            return handle_HFCUDA_cublasDcopy_v2();
        case HFCUDA_cublasDdgmm:
            return handle_HFCUDA_cublasDdgmm();
        case HFCUDA_cublasDdot_v2:
            return handle_HFCUDA_cublasDdot_v2();
        case HFCUDA_cublasDestroy_v2:
            return handle_HFCUDA_cublasDestroy_v2();
        case HFCUDA_cublasDgbmv_v2:
            return handle_HFCUDA_cublasDgbmv_v2();
        case HFCUDA_cublasDgeam:
            return handle_HFCUDA_cublasDgeam();
        case HFCUDA_cublasDgelsBatched:
            return handle_HFCUDA_cublasDgelsBatched();
        case HFCUDA_cublasDgemmBatched:
            return handle_HFCUDA_cublasDgemmBatched();
        case HFCUDA_cublasDgemmStridedBatched:
            return handle_HFCUDA_cublasDgemmStridedBatched();
        case HFCUDA_cublasDgemm_v2:
            return handle_HFCUDA_cublasDgemm_v2();
        case HFCUDA_cublasDgemv_v2:
            return handle_HFCUDA_cublasDgemv_v2();
        case HFCUDA_cublasDgeqrfBatched:
            return handle_HFCUDA_cublasDgeqrfBatched();
        case HFCUDA_cublasDger_v2:
            return handle_HFCUDA_cublasDger_v2();
        case HFCUDA_cublasDgetrfBatched:
            return handle_HFCUDA_cublasDgetrfBatched();
        case HFCUDA_cublasDgetriBatched:
            return handle_HFCUDA_cublasDgetriBatched();
        case HFCUDA_cublasDgetrsBatched:
            return handle_HFCUDA_cublasDgetrsBatched();
        case HFCUDA_cublasDmatinvBatched:
            return handle_HFCUDA_cublasDmatinvBatched();
        case HFCUDA_cublasDnrm2_v2:
            return handle_HFCUDA_cublasDnrm2_v2();
        case HFCUDA_cublasDrot_v2:
            return handle_HFCUDA_cublasDrot_v2();
        case HFCUDA_cublasDrotg_v2:
            return handle_HFCUDA_cublasDrotg_v2();
        case HFCUDA_cublasDrotm_v2:
            return handle_HFCUDA_cublasDrotm_v2();
        case HFCUDA_cublasDrotmg_v2:
            return handle_HFCUDA_cublasDrotmg_v2();
        case HFCUDA_cublasDsbmv_v2:
            return handle_HFCUDA_cublasDsbmv_v2();
        case HFCUDA_cublasDscal_v2:
            return handle_HFCUDA_cublasDscal_v2();
        case HFCUDA_cublasDspmv_v2:
            return handle_HFCUDA_cublasDspmv_v2();
        case HFCUDA_cublasDspr2_v2:
            return handle_HFCUDA_cublasDspr2_v2();
        case HFCUDA_cublasDspr_v2:
            return handle_HFCUDA_cublasDspr_v2();
        case HFCUDA_cublasDswap_v2:
            return handle_HFCUDA_cublasDswap_v2();
        case HFCUDA_cublasDsymm_v2:
            return handle_HFCUDA_cublasDsymm_v2();
        case HFCUDA_cublasDsymv_v2:
            return handle_HFCUDA_cublasDsymv_v2();
        case HFCUDA_cublasDsyr2_v2:
            return handle_HFCUDA_cublasDsyr2_v2();
        case HFCUDA_cublasDsyr2k_v2:
            return handle_HFCUDA_cublasDsyr2k_v2();
        case HFCUDA_cublasDsyr_v2:
            return handle_HFCUDA_cublasDsyr_v2();
        case HFCUDA_cublasDsyrk_v2:
            return handle_HFCUDA_cublasDsyrk_v2();
        case HFCUDA_cublasDsyrkx:
            return handle_HFCUDA_cublasDsyrkx();
        case HFCUDA_cublasDtbmv_v2:
            return handle_HFCUDA_cublasDtbmv_v2();
        case HFCUDA_cublasDtbsv_v2:
            return handle_HFCUDA_cublasDtbsv_v2();
        case HFCUDA_cublasDtpmv_v2:
            return handle_HFCUDA_cublasDtpmv_v2();
        case HFCUDA_cublasDtpsv_v2:
            return handle_HFCUDA_cublasDtpsv_v2();
        case HFCUDA_cublasDtpttr:
            return handle_HFCUDA_cublasDtpttr();
        case HFCUDA_cublasDtrmm_v2:
            return handle_HFCUDA_cublasDtrmm_v2();
        case HFCUDA_cublasDtrmv_v2:
            return handle_HFCUDA_cublasDtrmv_v2();
        case HFCUDA_cublasDtrsmBatched:
            return handle_HFCUDA_cublasDtrsmBatched();
        case HFCUDA_cublasDtrsm_v2:
            return handle_HFCUDA_cublasDtrsm_v2();
        case HFCUDA_cublasDtrsv_v2:
            return handle_HFCUDA_cublasDtrsv_v2();
        case HFCUDA_cublasDtrttp:
            return handle_HFCUDA_cublasDtrttp();
        case HFCUDA_cublasDzasum_v2:
            return handle_HFCUDA_cublasDzasum_v2();
        case HFCUDA_cublasDznrm2_v2:
            return handle_HFCUDA_cublasDznrm2_v2();
        case HFCUDA_cublasGemmBatchedEx:
            return handle_HFCUDA_cublasGemmBatchedEx();
        case HFCUDA_cublasGemmEx:
            return handle_HFCUDA_cublasGemmEx();
        case HFCUDA_cublasGemmStridedBatchedEx:
            return handle_HFCUDA_cublasGemmStridedBatchedEx();
        case HFCUDA_cublasGetAtomicsMode:
            return handle_HFCUDA_cublasGetAtomicsMode();
        case HFCUDA_cublasGetMathMode:
            return handle_HFCUDA_cublasGetMathMode();
        case HFCUDA_cublasGetProperty:
            return handle_HFCUDA_cublasGetProperty();
        case HFCUDA_cublasGetStream_v2:
            return handle_HFCUDA_cublasGetStream_v2();
        case HFCUDA_cublasGetVersion_v2:
            return handle_HFCUDA_cublasGetVersion_v2();
        case HFCUDA_cublasIcamax_v2:
            return handle_HFCUDA_cublasIcamax_v2();
        case HFCUDA_cublasIcamin_v2:
            return handle_HFCUDA_cublasIcamin_v2();
        case HFCUDA_cublasIdamax_v2:
            return handle_HFCUDA_cublasIdamax_v2();
        case HFCUDA_cublasIdamin_v2:
            return handle_HFCUDA_cublasIdamin_v2();
        case HFCUDA_cublasIsamax_v2:
            return handle_HFCUDA_cublasIsamax_v2();
        case HFCUDA_cublasIsamin_v2:
            return handle_HFCUDA_cublasIsamin_v2();
        case HFCUDA_cublasIzamax_v2:
            return handle_HFCUDA_cublasIzamax_v2();
        case HFCUDA_cublasIzamin_v2:
            return handle_HFCUDA_cublasIzamin_v2();
        case HFCUDA_cublasSasum_v2:
            return handle_HFCUDA_cublasSasum_v2();
        case HFCUDA_cublasSaxpy_v2:
            return handle_HFCUDA_cublasSaxpy_v2();
        case HFCUDA_cublasScalEx:
            return handle_HFCUDA_cublasScalEx();
        case HFCUDA_cublasScasum_v2:
            return handle_HFCUDA_cublasScasum_v2();
        case HFCUDA_cublasScnrm2_v2:
            return handle_HFCUDA_cublasScnrm2_v2();
        case HFCUDA_cublasScopy_v2:
            return handle_HFCUDA_cublasScopy_v2();
        case HFCUDA_cublasSdgmm:
            return handle_HFCUDA_cublasSdgmm();
        case HFCUDA_cublasSdot_v2:
            return handle_HFCUDA_cublasSdot_v2();
        case HFCUDA_cublasSetAtomicsMode:
            return handle_HFCUDA_cublasSetAtomicsMode();
        case HFCUDA_cublasSetMathMode:
            return handle_HFCUDA_cublasSetMathMode();
        case HFCUDA_cublasSetStream_v2:
            return handle_HFCUDA_cublasSetStream_v2();
        case HFCUDA_cublasSgbmv_v2:
            return handle_HFCUDA_cublasSgbmv_v2();
        case HFCUDA_cublasSgeam:
            return handle_HFCUDA_cublasSgeam();
        case HFCUDA_cublasSgelsBatched:
            return handle_HFCUDA_cublasSgelsBatched();
        case HFCUDA_cublasSgemmBatched:
            return handle_HFCUDA_cublasSgemmBatched();
        case HFCUDA_cublasSgemmEx:
            return handle_HFCUDA_cublasSgemmEx();
        case HFCUDA_cublasSgemmStridedBatched:
            return handle_HFCUDA_cublasSgemmStridedBatched();
        case HFCUDA_cublasSgemm_v2:
            return handle_HFCUDA_cublasSgemm_v2();
        case HFCUDA_cublasSgemv_v2:
            return handle_HFCUDA_cublasSgemv_v2();
        case HFCUDA_cublasSgeqrfBatched:
            return handle_HFCUDA_cublasSgeqrfBatched();
        case HFCUDA_cublasSger_v2:
            return handle_HFCUDA_cublasSger_v2();
        case HFCUDA_cublasSgetrfBatched:
            return handle_HFCUDA_cublasSgetrfBatched();
        case HFCUDA_cublasSgetriBatched:
            return handle_HFCUDA_cublasSgetriBatched();
        case HFCUDA_cublasSgetrsBatched:
            return handle_HFCUDA_cublasSgetrsBatched();
        case HFCUDA_cublasSmatinvBatched:
            return handle_HFCUDA_cublasSmatinvBatched();
        case HFCUDA_cublasSnrm2_v2:
            return handle_HFCUDA_cublasSnrm2_v2();
        case HFCUDA_cublasSrot_v2:
            return handle_HFCUDA_cublasSrot_v2();
        case HFCUDA_cublasSrotg_v2:
            return handle_HFCUDA_cublasSrotg_v2();
        case HFCUDA_cublasSrotm_v2:
            return handle_HFCUDA_cublasSrotm_v2();
        case HFCUDA_cublasSrotmg_v2:
            return handle_HFCUDA_cublasSrotmg_v2();
        case HFCUDA_cublasSsbmv_v2:
            return handle_HFCUDA_cublasSsbmv_v2();
        case HFCUDA_cublasSscal_v2:
            return handle_HFCUDA_cublasSscal_v2();
        case HFCUDA_cublasSspmv_v2:
            return handle_HFCUDA_cublasSspmv_v2();
        case HFCUDA_cublasSspr2_v2:
            return handle_HFCUDA_cublasSspr2_v2();
        case HFCUDA_cublasSspr_v2:
            return handle_HFCUDA_cublasSspr_v2();
        case HFCUDA_cublasSswap_v2:
            return handle_HFCUDA_cublasSswap_v2();
        case HFCUDA_cublasSsymm_v2:
            return handle_HFCUDA_cublasSsymm_v2();
        case HFCUDA_cublasSsymv_v2:
            return handle_HFCUDA_cublasSsymv_v2();
        case HFCUDA_cublasSsyr2_v2:
            return handle_HFCUDA_cublasSsyr2_v2();
        case HFCUDA_cublasSsyr2k_v2:
            return handle_HFCUDA_cublasSsyr2k_v2();
        case HFCUDA_cublasSsyr_v2:
            return handle_HFCUDA_cublasSsyr_v2();
        case HFCUDA_cublasSsyrk_v2:
            return handle_HFCUDA_cublasSsyrk_v2();
        case HFCUDA_cublasSsyrkx:
            return handle_HFCUDA_cublasSsyrkx();
        case HFCUDA_cublasStbmv_v2:
            return handle_HFCUDA_cublasStbmv_v2();
        case HFCUDA_cublasStbsv_v2:
            return handle_HFCUDA_cublasStbsv_v2();
        case HFCUDA_cublasStpmv_v2:
            return handle_HFCUDA_cublasStpmv_v2();
        case HFCUDA_cublasStpsv_v2:
            return handle_HFCUDA_cublasStpsv_v2();
        case HFCUDA_cublasStpttr:
            return handle_HFCUDA_cublasStpttr();
        case HFCUDA_cublasStrmm_v2:
            return handle_HFCUDA_cublasStrmm_v2();
        case HFCUDA_cublasStrmv_v2:
            return handle_HFCUDA_cublasStrmv_v2();
        case HFCUDA_cublasStrsmBatched:
            return handle_HFCUDA_cublasStrsmBatched();
        case HFCUDA_cublasStrsm_v2:
            return handle_HFCUDA_cublasStrsm_v2();
        case HFCUDA_cublasStrsv_v2:
            return handle_HFCUDA_cublasStrsv_v2();
        case HFCUDA_cublasStrttp:
            return handle_HFCUDA_cublasStrttp();
        case HFCUDA_cublasZaxpy_v2:
            return handle_HFCUDA_cublasZaxpy_v2();
        case HFCUDA_cublasZcopy_v2:
            return handle_HFCUDA_cublasZcopy_v2();
        case HFCUDA_cublasZdgmm:
            return handle_HFCUDA_cublasZdgmm();
        case HFCUDA_cublasZdotc_v2:
            return handle_HFCUDA_cublasZdotc_v2();
        case HFCUDA_cublasZdotu_v2:
            return handle_HFCUDA_cublasZdotu_v2();
        case HFCUDA_cublasZdrot_v2:
            return handle_HFCUDA_cublasZdrot_v2();
        case HFCUDA_cublasZdscal_v2:
            return handle_HFCUDA_cublasZdscal_v2();
        case HFCUDA_cublasZgbmv_v2:
            return handle_HFCUDA_cublasZgbmv_v2();
        case HFCUDA_cublasZgeam:
            return handle_HFCUDA_cublasZgeam();
        case HFCUDA_cublasZgelsBatched:
            return handle_HFCUDA_cublasZgelsBatched();
        case HFCUDA_cublasZgemmBatched:
            return handle_HFCUDA_cublasZgemmBatched();
        case HFCUDA_cublasZgemmStridedBatched:
            return handle_HFCUDA_cublasZgemmStridedBatched();
        case HFCUDA_cublasZgemm_v2:
            return handle_HFCUDA_cublasZgemm_v2();
        case HFCUDA_cublasZgemv_v2:
            return handle_HFCUDA_cublasZgemv_v2();
        case HFCUDA_cublasZgeqrfBatched:
            return handle_HFCUDA_cublasZgeqrfBatched();
        case HFCUDA_cublasZgerc_v2:
            return handle_HFCUDA_cublasZgerc_v2();
        case HFCUDA_cublasZgeru_v2:
            return handle_HFCUDA_cublasZgeru_v2();
        case HFCUDA_cublasZgetrfBatched:
            return handle_HFCUDA_cublasZgetrfBatched();
        case HFCUDA_cublasZgetriBatched:
            return handle_HFCUDA_cublasZgetriBatched();
        case HFCUDA_cublasZgetrsBatched:
            return handle_HFCUDA_cublasZgetrsBatched();
        case HFCUDA_cublasZhbmv_v2:
            return handle_HFCUDA_cublasZhbmv_v2();
        case HFCUDA_cublasZhemm_v2:
            return handle_HFCUDA_cublasZhemm_v2();
        case HFCUDA_cublasZhemv_v2:
            return handle_HFCUDA_cublasZhemv_v2();
        case HFCUDA_cublasZher2_v2:
            return handle_HFCUDA_cublasZher2_v2();
        case HFCUDA_cublasZher2k_v2:
            return handle_HFCUDA_cublasZher2k_v2();
        case HFCUDA_cublasZher_v2:
            return handle_HFCUDA_cublasZher_v2();
        case HFCUDA_cublasZherk_v2:
            return handle_HFCUDA_cublasZherk_v2();
        case HFCUDA_cublasZherkx:
            return handle_HFCUDA_cublasZherkx();
        case HFCUDA_cublasZhpmv_v2:
            return handle_HFCUDA_cublasZhpmv_v2();
        case HFCUDA_cublasZhpr2_v2:
            return handle_HFCUDA_cublasZhpr2_v2();
        case HFCUDA_cublasZhpr_v2:
            return handle_HFCUDA_cublasZhpr_v2();
        case HFCUDA_cublasZmatinvBatched:
            return handle_HFCUDA_cublasZmatinvBatched();
        case HFCUDA_cublasZrot_v2:
            return handle_HFCUDA_cublasZrot_v2();
        case HFCUDA_cublasZrotg_v2:
            return handle_HFCUDA_cublasZrotg_v2();
        case HFCUDA_cublasZscal_v2:
            return handle_HFCUDA_cublasZscal_v2();
        case HFCUDA_cublasZswap_v2:
            return handle_HFCUDA_cublasZswap_v2();
        case HFCUDA_cublasZsymm_v2:
            return handle_HFCUDA_cublasZsymm_v2();
        case HFCUDA_cublasZsymv_v2:
            return handle_HFCUDA_cublasZsymv_v2();
        case HFCUDA_cublasZsyr2_v2:
            return handle_HFCUDA_cublasZsyr2_v2();
        case HFCUDA_cublasZsyr2k_v2:
            return handle_HFCUDA_cublasZsyr2k_v2();
        case HFCUDA_cublasZsyr_v2:
            return handle_HFCUDA_cublasZsyr_v2();
        case HFCUDA_cublasZsyrk_v2:
            return handle_HFCUDA_cublasZsyrk_v2();
        case HFCUDA_cublasZsyrkx:
            return handle_HFCUDA_cublasZsyrkx();
        case HFCUDA_cublasZtbmv_v2:
            return handle_HFCUDA_cublasZtbmv_v2();
        case HFCUDA_cublasZtbsv_v2:
            return handle_HFCUDA_cublasZtbsv_v2();
        case HFCUDA_cublasZtpmv_v2:
            return handle_HFCUDA_cublasZtpmv_v2();
        case HFCUDA_cublasZtpsv_v2:
            return handle_HFCUDA_cublasZtpsv_v2();
        case HFCUDA_cublasZtpttr:
            return handle_HFCUDA_cublasZtpttr();
        case HFCUDA_cublasZtrmm_v2:
            return handle_HFCUDA_cublasZtrmm_v2();
        case HFCUDA_cublasZtrmv_v2:
            return handle_HFCUDA_cublasZtrmv_v2();
        case HFCUDA_cublasZtrsmBatched:
            return handle_HFCUDA_cublasZtrsmBatched();
        case HFCUDA_cublasZtrsm_v2:
            return handle_HFCUDA_cublasZtrsm_v2();
        case HFCUDA_cublasZtrsv_v2:
            return handle_HFCUDA_cublasZtrsv_v2();
        case HFCUDA_cublasZtrttp:
            return handle_HFCUDA_cublasZtrttp();
        case HFCUDA_cudaDeviceGetAttribute:
            return handle_HFCUDA_cudaDeviceGetAttribute();
        case HFCUDA_cudaDeviceGetCacheConfig:
            return handle_HFCUDA_cudaDeviceGetCacheConfig();
        case HFCUDA_cudaDeviceGetLimit:
            return handle_HFCUDA_cudaDeviceGetLimit();
        case HFCUDA_cudaDeviceGetSharedMemConfig:
            return handle_HFCUDA_cudaDeviceGetSharedMemConfig();
        case HFCUDA_cudaDeviceGetStreamPriorityRange:
            return handle_HFCUDA_cudaDeviceGetStreamPriorityRange();
        case HFCUDA_cudaDeviceReset:
            return handle_HFCUDA_cudaDeviceReset();
        case HFCUDA_cudaDeviceSetCacheConfig:
            return handle_HFCUDA_cudaDeviceSetCacheConfig();
        case HFCUDA_cudaDeviceSetLimit:
            return handle_HFCUDA_cudaDeviceSetLimit();
        case HFCUDA_cudaDeviceSetSharedMemConfig:
            return handle_HFCUDA_cudaDeviceSetSharedMemConfig();
        case HFCUDA_cudaDeviceSynchronize:
            return handle_HFCUDA_cudaDeviceSynchronize();
        case HFCUDA_cudaDriverGetVersion:
            return handle_HFCUDA_cudaDriverGetVersion();
        case HFCUDA_cudaEventCreate:
            return handle_HFCUDA_cudaEventCreate();
        case HFCUDA_cudaEventCreateWithFlags:
            return handle_HFCUDA_cudaEventCreateWithFlags();
        case HFCUDA_cudaEventDestroy:
            return handle_HFCUDA_cudaEventDestroy();
        case HFCUDA_cudaEventElapsedTime:
            return handle_HFCUDA_cudaEventElapsedTime();
        case HFCUDA_cudaEventQuery:
            return handle_HFCUDA_cudaEventQuery();
        case HFCUDA_cudaEventRecord:
            return handle_HFCUDA_cudaEventRecord();
        case HFCUDA_cudaEventSynchronize:
            return handle_HFCUDA_cudaEventSynchronize();
        case HFCUDA_cudaGetDeviceFlags:
            return handle_HFCUDA_cudaGetDeviceFlags();
        case HFCUDA_cudaGetLastError:
            return handle_HFCUDA_cudaGetLastError();
        case HFCUDA_cudaMemset:
            return handle_HFCUDA_cudaMemset();
        case HFCUDA_cudaMemset2D:
            return handle_HFCUDA_cudaMemset2D();
        case HFCUDA_cudaMemset3D:
            return handle_HFCUDA_cudaMemset3D();
        case HFCUDA_cudaPeekAtLastError:
            return handle_HFCUDA_cudaPeekAtLastError();
        case HFCUDA_cudaRuntimeGetVersion:
            return handle_HFCUDA_cudaRuntimeGetVersion();
        case HFCUDA_cudaSetDeviceFlags:
            return handle_HFCUDA_cudaSetDeviceFlags();
        case HFCUDA_cudaStreamCreate:
            return handle_HFCUDA_cudaStreamCreate();
        case HFCUDA_cudaStreamCreateWithFlags:
            return handle_HFCUDA_cudaStreamCreateWithFlags();
        case HFCUDA_cudaStreamCreateWithPriority:
            return handle_HFCUDA_cudaStreamCreateWithPriority();
        case HFCUDA_cudaStreamDestroy:
            return handle_HFCUDA_cudaStreamDestroy();
        case HFCUDA_cudaStreamGetFlags:
            return handle_HFCUDA_cudaStreamGetFlags();
        case HFCUDA_cudaStreamGetPriority:
            return handle_HFCUDA_cudaStreamGetPriority();
        case HFCUDA_cudaStreamQuery:
            return handle_HFCUDA_cudaStreamQuery();
        case HFCUDA_cudaStreamSynchronize:
            return handle_HFCUDA_cudaStreamSynchronize();
        case HFCUDA_cudaStreamWaitEvent:
            return handle_HFCUDA_cudaStreamWaitEvent();
        case HFCUDA_cudaThreadExit:
            return handle_HFCUDA_cudaThreadExit();
        case HFCUDA_cudaThreadGetCacheConfig:
            return handle_HFCUDA_cudaThreadGetCacheConfig();
        case HFCUDA_cudaThreadGetLimit:
            return handle_HFCUDA_cudaThreadGetLimit();
        case HFCUDA_cudaThreadSetCacheConfig:
            return handle_HFCUDA_cudaThreadSetCacheConfig();
        case HFCUDA_cudaThreadSetLimit:
            return handle_HFCUDA_cudaThreadSetLimit();
        case HFCUDA_cudaThreadSynchronize:
            return handle_HFCUDA_cudaThreadSynchronize();
        case HFCUDA_cudnnActivationBackward:
            return handle_HFCUDA_cudnnActivationBackward();
        case HFCUDA_cudnnActivationForward:
            return handle_HFCUDA_cudnnActivationForward();
        case HFCUDA_cudnnAddTensor:
            return handle_HFCUDA_cudnnAddTensor();
        case HFCUDA_cudnnBatchNormalizationBackward:
            return handle_HFCUDA_cudnnBatchNormalizationBackward();
        case HFCUDA_cudnnBatchNormalizationForwardInference:
            return handle_HFCUDA_cudnnBatchNormalizationForwardInference();
        case HFCUDA_cudnnBatchNormalizationForwardTraining:
            return handle_HFCUDA_cudnnBatchNormalizationForwardTraining();
        case HFCUDA_cudnnConvolutionBackwardBias:
            return handle_HFCUDA_cudnnConvolutionBackwardBias();
        case HFCUDA_cudnnConvolutionBackwardData:
            return handle_HFCUDA_cudnnConvolutionBackwardData();
        case HFCUDA_cudnnConvolutionBackwardFilter:
            return handle_HFCUDA_cudnnConvolutionBackwardFilter();
        case HFCUDA_cudnnConvolutionForward:
            return handle_HFCUDA_cudnnConvolutionForward();
        case HFCUDA_cudnnCreate:
            return handle_HFCUDA_cudnnCreate();
        case HFCUDA_cudnnCreateActivationDescriptor:
            return handle_HFCUDA_cudnnCreateActivationDescriptor();
        case HFCUDA_cudnnCreateConvolutionDescriptor:
            return handle_HFCUDA_cudnnCreateConvolutionDescriptor();
        case HFCUDA_cudnnCreateDropoutDescriptor:
            return handle_HFCUDA_cudnnCreateDropoutDescriptor();
        case HFCUDA_cudnnCreateFilterDescriptor:
            return handle_HFCUDA_cudnnCreateFilterDescriptor();
        case HFCUDA_cudnnCreateLRNDescriptor:
            return handle_HFCUDA_cudnnCreateLRNDescriptor();
        case HFCUDA_cudnnCreateOpTensorDescriptor:
            return handle_HFCUDA_cudnnCreateOpTensorDescriptor();
        case HFCUDA_cudnnCreatePoolingDescriptor:
            return handle_HFCUDA_cudnnCreatePoolingDescriptor();
        case HFCUDA_cudnnCreateRNNDescriptor:
            return handle_HFCUDA_cudnnCreateRNNDescriptor();
        case HFCUDA_cudnnCreateSpatialTransformerDescriptor:
            return handle_HFCUDA_cudnnCreateSpatialTransformerDescriptor();
        case HFCUDA_cudnnCreateTensorDescriptor:
            return handle_HFCUDA_cudnnCreateTensorDescriptor();
        case HFCUDA_cudnnDeriveBNTensorDescriptor:
            return handle_HFCUDA_cudnnDeriveBNTensorDescriptor();
        case HFCUDA_cudnnDestroy:
            return handle_HFCUDA_cudnnDestroy();
        case HFCUDA_cudnnDestroyActivationDescriptor:
            return handle_HFCUDA_cudnnDestroyActivationDescriptor();
        case HFCUDA_cudnnDestroyConvolutionDescriptor:
            return handle_HFCUDA_cudnnDestroyConvolutionDescriptor();
        case HFCUDA_cudnnDestroyDropoutDescriptor:
            return handle_HFCUDA_cudnnDestroyDropoutDescriptor();
        case HFCUDA_cudnnDestroyFilterDescriptor:
            return handle_HFCUDA_cudnnDestroyFilterDescriptor();
        case HFCUDA_cudnnDestroyLRNDescriptor:
            return handle_HFCUDA_cudnnDestroyLRNDescriptor();
        case HFCUDA_cudnnDestroyOpTensorDescriptor:
            return handle_HFCUDA_cudnnDestroyOpTensorDescriptor();
        case HFCUDA_cudnnDestroyPoolingDescriptor:
            return handle_HFCUDA_cudnnDestroyPoolingDescriptor();
        case HFCUDA_cudnnDestroyRNNDescriptor:
            return handle_HFCUDA_cudnnDestroyRNNDescriptor();
        case HFCUDA_cudnnDestroySpatialTransformerDescriptor:
            return handle_HFCUDA_cudnnDestroySpatialTransformerDescriptor();
        case HFCUDA_cudnnDestroyTensorDescriptor:
            return handle_HFCUDA_cudnnDestroyTensorDescriptor();
        case HFCUDA_cudnnDivisiveNormalizationBackward:
            return handle_HFCUDA_cudnnDivisiveNormalizationBackward();
        case HFCUDA_cudnnDivisiveNormalizationForward:
            return handle_HFCUDA_cudnnDivisiveNormalizationForward();
        case HFCUDA_cudnnDropoutBackward:
            return handle_HFCUDA_cudnnDropoutBackward();
        case HFCUDA_cudnnDropoutForward:
            return handle_HFCUDA_cudnnDropoutForward();
        case HFCUDA_cudnnDropoutGetReserveSpaceSize:
            return handle_HFCUDA_cudnnDropoutGetReserveSpaceSize();
        case HFCUDA_cudnnDropoutGetStatesSize:
            return handle_HFCUDA_cudnnDropoutGetStatesSize();
        case HFCUDA_cudnnGetActivationDescriptor:
            return handle_HFCUDA_cudnnGetActivationDescriptor();
        case HFCUDA_cudnnGetConvolution2dDescriptor:
            return handle_HFCUDA_cudnnGetConvolution2dDescriptor();
        case HFCUDA_cudnnGetConvolution2dForwardOutputDim:
            return handle_HFCUDA_cudnnGetConvolution2dForwardOutputDim();
        case HFCUDA_cudnnGetConvolutionBackwardDataAlgorithm:
            return handle_HFCUDA_cudnnGetConvolutionBackwardDataAlgorithm();
        case HFCUDA_cudnnGetConvolutionBackwardDataWorkspaceSize:
            return handle_HFCUDA_cudnnGetConvolutionBackwardDataWorkspaceSize();
        case HFCUDA_cudnnGetConvolutionBackwardFilterAlgorithm:
            return handle_HFCUDA_cudnnGetConvolutionBackwardFilterAlgorithm();
        case HFCUDA_cudnnGetConvolutionBackwardFilterWorkspaceSize:
            return handle_HFCUDA_cudnnGetConvolutionBackwardFilterWorkspaceSize();
        case HFCUDA_cudnnGetConvolutionForwardAlgorithm:
            return handle_HFCUDA_cudnnGetConvolutionForwardAlgorithm();
        case HFCUDA_cudnnGetConvolutionForwardWorkspaceSize:
            return handle_HFCUDA_cudnnGetConvolutionForwardWorkspaceSize();
        case HFCUDA_cudnnGetFilter4dDescriptor:
            return handle_HFCUDA_cudnnGetFilter4dDescriptor();
        case HFCUDA_cudnnGetLRNDescriptor:
            return handle_HFCUDA_cudnnGetLRNDescriptor();
        case HFCUDA_cudnnGetOpTensorDescriptor:
            return handle_HFCUDA_cudnnGetOpTensorDescriptor();
        case HFCUDA_cudnnGetPooling2dDescriptor:
            return handle_HFCUDA_cudnnGetPooling2dDescriptor();
        case HFCUDA_cudnnGetPooling2dForwardOutputDim:
            return handle_HFCUDA_cudnnGetPooling2dForwardOutputDim();
        case HFCUDA_cudnnGetRNNLinLayerBiasParams:
            return handle_HFCUDA_cudnnGetRNNLinLayerBiasParams();
        case HFCUDA_cudnnGetRNNLinLayerMatrixParams:
            return handle_HFCUDA_cudnnGetRNNLinLayerMatrixParams();
        case HFCUDA_cudnnGetRNNParamsSize:
            return handle_HFCUDA_cudnnGetRNNParamsSize();
        case HFCUDA_cudnnGetStream:
            return handle_HFCUDA_cudnnGetStream();
        case HFCUDA_cudnnGetTensor4dDescriptor:
            return handle_HFCUDA_cudnnGetTensor4dDescriptor();
        case HFCUDA_cudnnGetVersion:
            return handle_HFCUDA_cudnnGetVersion();
        case HFCUDA_cudnnIm2Col:
            return handle_HFCUDA_cudnnIm2Col();
        case HFCUDA_cudnnLRNCrossChannelBackward:
            return handle_HFCUDA_cudnnLRNCrossChannelBackward();
        case HFCUDA_cudnnLRNCrossChannelForward:
            return handle_HFCUDA_cudnnLRNCrossChannelForward();
        case HFCUDA_cudnnOpTensor:
            return handle_HFCUDA_cudnnOpTensor();
        case HFCUDA_cudnnPoolingBackward:
            return handle_HFCUDA_cudnnPoolingBackward();
        case HFCUDA_cudnnPoolingForward:
            return handle_HFCUDA_cudnnPoolingForward();
        case HFCUDA_cudnnRNNBackwardData:
            return handle_HFCUDA_cudnnRNNBackwardData();
        case HFCUDA_cudnnRNNBackwardWeights:
            return handle_HFCUDA_cudnnRNNBackwardWeights();
        case HFCUDA_cudnnRNNForwardInference:
            return handle_HFCUDA_cudnnRNNForwardInference();
        case HFCUDA_cudnnRNNForwardTraining:
            return handle_HFCUDA_cudnnRNNForwardTraining();
        case HFCUDA_cudnnScaleTensor:
            return handle_HFCUDA_cudnnScaleTensor();
        case HFCUDA_cudnnSetActivationDescriptor:
            return handle_HFCUDA_cudnnSetActivationDescriptor();
        case HFCUDA_cudnnSetConvolution2dDescriptor:
            return handle_HFCUDA_cudnnSetConvolution2dDescriptor();
        case HFCUDA_cudnnSetConvolutionNdDescriptor:
            return handle_HFCUDA_cudnnSetConvolutionNdDescriptor();
        case HFCUDA_cudnnSetDropoutDescriptor:
            return handle_HFCUDA_cudnnSetDropoutDescriptor();
        case HFCUDA_cudnnSetFilter4dDescriptor:
            return handle_HFCUDA_cudnnSetFilter4dDescriptor();
        case HFCUDA_cudnnSetFilterNdDescriptor:
            return handle_HFCUDA_cudnnSetFilterNdDescriptor();
        case HFCUDA_cudnnSetLRNDescriptor:
            return handle_HFCUDA_cudnnSetLRNDescriptor();
        case HFCUDA_cudnnSetOpTensorDescriptor:
            return handle_HFCUDA_cudnnSetOpTensorDescriptor();
        case HFCUDA_cudnnSetPooling2dDescriptor:
            return handle_HFCUDA_cudnnSetPooling2dDescriptor();
        case HFCUDA_cudnnSetRNNDescriptor:
            return handle_HFCUDA_cudnnSetRNNDescriptor();
        case HFCUDA_cudnnSetSpatialTransformerNdDescriptor:
            return handle_HFCUDA_cudnnSetSpatialTransformerNdDescriptor();
        case HFCUDA_cudnnSetStream:
            return handle_HFCUDA_cudnnSetStream();
        case HFCUDA_cudnnSetTensor:
            return handle_HFCUDA_cudnnSetTensor();
        case HFCUDA_cudnnSetTensor4dDescriptor:
            return handle_HFCUDA_cudnnSetTensor4dDescriptor();
        case HFCUDA_cudnnSetTensor4dDescriptorEx:
            return handle_HFCUDA_cudnnSetTensor4dDescriptorEx();
        case HFCUDA_cudnnSetTensorNdDescriptor:
            return handle_HFCUDA_cudnnSetTensorNdDescriptor();
        case HFCUDA_cudnnSoftmaxBackward:
            return handle_HFCUDA_cudnnSoftmaxBackward();
        case HFCUDA_cudnnSoftmaxForward:
            return handle_HFCUDA_cudnnSoftmaxForward();
        case HFCUDA_cudnnSpatialTfGridGeneratorBackward:
            return handle_HFCUDA_cudnnSpatialTfGridGeneratorBackward();
        case HFCUDA_cudnnSpatialTfSamplerBackward:
            return handle_HFCUDA_cudnnSpatialTfSamplerBackward();
        case HFCUDA_cudnnSpatialTfSamplerForward:
            return handle_HFCUDA_cudnnSpatialTfSamplerForward();
        case HFCUDA_cudnnTransformTensor:
            return handle_HFCUDA_cudnnTransformTensor();
        case HFCUDA_cusparseCaxpyi:
            return handle_HFCUDA_cusparseCaxpyi();
        case HFCUDA_cusparseCbsr2csr:
            return handle_HFCUDA_cusparseCbsr2csr();
        case HFCUDA_cusparseCbsrmm:
            return handle_HFCUDA_cusparseCbsrmm();
        case HFCUDA_cusparseCbsrmv:
            return handle_HFCUDA_cusparseCbsrmv();
        case HFCUDA_cusparseCbsrsm2_analysis:
            return handle_HFCUDA_cusparseCbsrsm2_analysis();
        case HFCUDA_cusparseCbsrsm2_bufferSize:
            return handle_HFCUDA_cusparseCbsrsm2_bufferSize();
        case HFCUDA_cusparseCbsrsm2_solve:
            return handle_HFCUDA_cusparseCbsrsm2_solve();
        case HFCUDA_cusparseCbsrsv2_analysis:
            return handle_HFCUDA_cusparseCbsrsv2_analysis();
        case HFCUDA_cusparseCbsrsv2_bufferSize:
            return handle_HFCUDA_cusparseCbsrsv2_bufferSize();
        case HFCUDA_cusparseCbsrsv2_solve:
            return handle_HFCUDA_cusparseCbsrsv2_solve();
        case HFCUDA_cusparseCbsrxmv:
            return handle_HFCUDA_cusparseCbsrxmv();
        case HFCUDA_cusparseCcsc2dense:
            return handle_HFCUDA_cusparseCcsc2dense();
        case HFCUDA_cusparseCcsc2hyb:
            return handle_HFCUDA_cusparseCcsc2hyb();
        case HFCUDA_cusparseCcsr2bsr:
            return handle_HFCUDA_cusparseCcsr2bsr();
        case HFCUDA_cusparseCcsr2csc:
            return handle_HFCUDA_cusparseCcsr2csc();
        case HFCUDA_cusparseCcsr2csr_compress:
            return handle_HFCUDA_cusparseCcsr2csr_compress();
        case HFCUDA_cusparseCcsr2csru:
            return handle_HFCUDA_cusparseCcsr2csru();
        case HFCUDA_cusparseCcsr2dense:
            return handle_HFCUDA_cusparseCcsr2dense();
        case HFCUDA_cusparseCcsr2gebsr:
            return handle_HFCUDA_cusparseCcsr2gebsr();
        case HFCUDA_cusparseCcsr2gebsr_bufferSize:
            return handle_HFCUDA_cusparseCcsr2gebsr_bufferSize();
        case HFCUDA_cusparseCcsr2hyb:
            return handle_HFCUDA_cusparseCcsr2hyb();
        case HFCUDA_cusparseCcsrcolor:
            return handle_HFCUDA_cusparseCcsrcolor();
        case HFCUDA_cusparseCcsrgeam:
            return handle_HFCUDA_cusparseCcsrgeam();
        case HFCUDA_cusparseCcsrgemm:
            return handle_HFCUDA_cusparseCcsrgemm();
        case HFCUDA_cusparseCcsrgemm2:
            return handle_HFCUDA_cusparseCcsrgemm2();
        case HFCUDA_cusparseCcsrgemm2_bufferSizeExt:
            return handle_HFCUDA_cusparseCcsrgemm2_bufferSizeExt();
        case HFCUDA_cusparseCcsrmm:
            return handle_HFCUDA_cusparseCcsrmm();
        case HFCUDA_cusparseCcsrmm2:
            return handle_HFCUDA_cusparseCcsrmm2();
        case HFCUDA_cusparseCcsrmv:
            return handle_HFCUDA_cusparseCcsrmv();
        case HFCUDA_cusparseCcsrmv_mp:
            return handle_HFCUDA_cusparseCcsrmv_mp();
        case HFCUDA_cusparseCcsrsm_analysis:
            return handle_HFCUDA_cusparseCcsrsm_analysis();
        case HFCUDA_cusparseCcsrsm_solve:
            return handle_HFCUDA_cusparseCcsrsm_solve();
        case HFCUDA_cusparseCcsrsv2_analysis:
            return handle_HFCUDA_cusparseCcsrsv2_analysis();
        case HFCUDA_cusparseCcsrsv2_bufferSize:
            return handle_HFCUDA_cusparseCcsrsv2_bufferSize();
        case HFCUDA_cusparseCcsrsv2_solve:
            return handle_HFCUDA_cusparseCcsrsv2_solve();
        case HFCUDA_cusparseCcsrsv_analysis:
            return handle_HFCUDA_cusparseCcsrsv_analysis();
        case HFCUDA_cusparseCcsrsv_solve:
            return handle_HFCUDA_cusparseCcsrsv_solve();
        case HFCUDA_cusparseCcsru2csr:
            return handle_HFCUDA_cusparseCcsru2csr();
        case HFCUDA_cusparseCcsru2csr_bufferSizeExt:
            return handle_HFCUDA_cusparseCcsru2csr_bufferSizeExt();
        case HFCUDA_cusparseCdense2csc:
            return handle_HFCUDA_cusparseCdense2csc();
        case HFCUDA_cusparseCdense2csr:
            return handle_HFCUDA_cusparseCdense2csr();
        case HFCUDA_cusparseCdense2hyb:
            return handle_HFCUDA_cusparseCdense2hyb();
        case HFCUDA_cusparseCdotci:
            return handle_HFCUDA_cusparseCdotci();
        case HFCUDA_cusparseCdoti:
            return handle_HFCUDA_cusparseCdoti();
        case HFCUDA_cusparseCgebsr2csr:
            return handle_HFCUDA_cusparseCgebsr2csr();
        case HFCUDA_cusparseCgebsr2gebsc:
            return handle_HFCUDA_cusparseCgebsr2gebsc();
        case HFCUDA_cusparseCgebsr2gebsc_bufferSize:
            return handle_HFCUDA_cusparseCgebsr2gebsc_bufferSize();
        case HFCUDA_cusparseCgebsr2gebsr:
            return handle_HFCUDA_cusparseCgebsr2gebsr();
        case HFCUDA_cusparseCgebsr2gebsr_bufferSize:
            return handle_HFCUDA_cusparseCgebsr2gebsr_bufferSize();
        case HFCUDA_cusparseCgemmi:
            return handle_HFCUDA_cusparseCgemmi();
        case HFCUDA_cusparseCgemvi:
            return handle_HFCUDA_cusparseCgemvi();
        case HFCUDA_cusparseCgemvi_bufferSize:
            return handle_HFCUDA_cusparseCgemvi_bufferSize();
        case HFCUDA_cusparseCgthr:
            return handle_HFCUDA_cusparseCgthr();
        case HFCUDA_cusparseCgthrz:
            return handle_HFCUDA_cusparseCgthrz();
        case HFCUDA_cusparseChyb2csc:
            return handle_HFCUDA_cusparseChyb2csc();
        case HFCUDA_cusparseChyb2csr:
            return handle_HFCUDA_cusparseChyb2csr();
        case HFCUDA_cusparseChyb2dense:
            return handle_HFCUDA_cusparseChyb2dense();
        case HFCUDA_cusparseChybmv:
            return handle_HFCUDA_cusparseChybmv();
        case HFCUDA_cusparseChybsv_analysis:
            return handle_HFCUDA_cusparseChybsv_analysis();
        case HFCUDA_cusparseChybsv_solve:
            return handle_HFCUDA_cusparseChybsv_solve();
        case HFCUDA_cusparseCnnz:
            return handle_HFCUDA_cusparseCnnz();
        case HFCUDA_cusparseCnnz_compress:
            return handle_HFCUDA_cusparseCnnz_compress();
        case HFCUDA_cusparseCreate:
            return handle_HFCUDA_cusparseCreate();
        case HFCUDA_cusparseCreateBsric02Info:
            return handle_HFCUDA_cusparseCreateBsric02Info();
        case HFCUDA_cusparseCreateBsrilu02Info:
            return handle_HFCUDA_cusparseCreateBsrilu02Info();
        case HFCUDA_cusparseCreateBsrsm2Info:
            return handle_HFCUDA_cusparseCreateBsrsm2Info();
        case HFCUDA_cusparseCreateBsrsv2Info:
            return handle_HFCUDA_cusparseCreateBsrsv2Info();
        case HFCUDA_cusparseCreateCsrgemm2Info:
            return handle_HFCUDA_cusparseCreateCsrgemm2Info();
        case HFCUDA_cusparseCreateCsric02Info:
            return handle_HFCUDA_cusparseCreateCsric02Info();
        case HFCUDA_cusparseCreateCsrilu02Info:
            return handle_HFCUDA_cusparseCreateCsrilu02Info();
        case HFCUDA_cusparseCreateCsrsv2Info:
            return handle_HFCUDA_cusparseCreateCsrsv2Info();
        case HFCUDA_cusparseCreateCsru2csrInfo:
            return handle_HFCUDA_cusparseCreateCsru2csrInfo();
        case HFCUDA_cusparseCreateHybMat:
            return handle_HFCUDA_cusparseCreateHybMat();
        case HFCUDA_cusparseCreateIdentityPermutation:
            return handle_HFCUDA_cusparseCreateIdentityPermutation();
        case HFCUDA_cusparseCreateMatDescr:
            return handle_HFCUDA_cusparseCreateMatDescr();
        case HFCUDA_cusparseCreatePruneInfo:
            return handle_HFCUDA_cusparseCreatePruneInfo();
        case HFCUDA_cusparseCreateSolveAnalysisInfo:
            return handle_HFCUDA_cusparseCreateSolveAnalysisInfo();
        case HFCUDA_cusparseCsctr:
            return handle_HFCUDA_cusparseCsctr();
        case HFCUDA_cusparseCsr2cscEx:
            return handle_HFCUDA_cusparseCsr2cscEx();
        case HFCUDA_cusparseCsrmvEx:
            return handle_HFCUDA_cusparseCsrmvEx();
        case HFCUDA_cusparseCsrmvEx_bufferSize:
            return handle_HFCUDA_cusparseCsrmvEx_bufferSize();
        case HFCUDA_cusparseCsrsv_analysisEx:
            return handle_HFCUDA_cusparseCsrsv_analysisEx();
        case HFCUDA_cusparseCsrsv_solveEx:
            return handle_HFCUDA_cusparseCsrsv_solveEx();
        case HFCUDA_cusparseDaxpyi:
            return handle_HFCUDA_cusparseDaxpyi();
        case HFCUDA_cusparseDbsr2csr:
            return handle_HFCUDA_cusparseDbsr2csr();
        case HFCUDA_cusparseDbsrmm:
            return handle_HFCUDA_cusparseDbsrmm();
        case HFCUDA_cusparseDbsrmv:
            return handle_HFCUDA_cusparseDbsrmv();
        case HFCUDA_cusparseDbsrsm2_analysis:
            return handle_HFCUDA_cusparseDbsrsm2_analysis();
        case HFCUDA_cusparseDbsrsm2_bufferSize:
            return handle_HFCUDA_cusparseDbsrsm2_bufferSize();
        case HFCUDA_cusparseDbsrsm2_solve:
            return handle_HFCUDA_cusparseDbsrsm2_solve();
        case HFCUDA_cusparseDbsrsv2_analysis:
            return handle_HFCUDA_cusparseDbsrsv2_analysis();
        case HFCUDA_cusparseDbsrsv2_bufferSize:
            return handle_HFCUDA_cusparseDbsrsv2_bufferSize();
        case HFCUDA_cusparseDbsrsv2_solve:
            return handle_HFCUDA_cusparseDbsrsv2_solve();
        case HFCUDA_cusparseDbsrxmv:
            return handle_HFCUDA_cusparseDbsrxmv();
        case HFCUDA_cusparseDcsc2dense:
            return handle_HFCUDA_cusparseDcsc2dense();
        case HFCUDA_cusparseDcsc2hyb:
            return handle_HFCUDA_cusparseDcsc2hyb();
        case HFCUDA_cusparseDcsr2bsr:
            return handle_HFCUDA_cusparseDcsr2bsr();
        case HFCUDA_cusparseDcsr2csc:
            return handle_HFCUDA_cusparseDcsr2csc();
        case HFCUDA_cusparseDcsr2csr_compress:
            return handle_HFCUDA_cusparseDcsr2csr_compress();
        case HFCUDA_cusparseDcsr2csru:
            return handle_HFCUDA_cusparseDcsr2csru();
        case HFCUDA_cusparseDcsr2dense:
            return handle_HFCUDA_cusparseDcsr2dense();
        case HFCUDA_cusparseDcsr2gebsr:
            return handle_HFCUDA_cusparseDcsr2gebsr();
        case HFCUDA_cusparseDcsr2gebsr_bufferSize:
            return handle_HFCUDA_cusparseDcsr2gebsr_bufferSize();
        case HFCUDA_cusparseDcsr2hyb:
            return handle_HFCUDA_cusparseDcsr2hyb();
        case HFCUDA_cusparseDcsrcolor:
            return handle_HFCUDA_cusparseDcsrcolor();
        case HFCUDA_cusparseDcsrgeam:
            return handle_HFCUDA_cusparseDcsrgeam();
        case HFCUDA_cusparseDcsrgemm:
            return handle_HFCUDA_cusparseDcsrgemm();
        case HFCUDA_cusparseDcsrgemm2:
            return handle_HFCUDA_cusparseDcsrgemm2();
        case HFCUDA_cusparseDcsrgemm2_bufferSizeExt:
            return handle_HFCUDA_cusparseDcsrgemm2_bufferSizeExt();
        case HFCUDA_cusparseDcsrmm:
            return handle_HFCUDA_cusparseDcsrmm();
        case HFCUDA_cusparseDcsrmm2:
            return handle_HFCUDA_cusparseDcsrmm2();
        case HFCUDA_cusparseDcsrmv:
            return handle_HFCUDA_cusparseDcsrmv();
        case HFCUDA_cusparseDcsrmv_mp:
            return handle_HFCUDA_cusparseDcsrmv_mp();
        case HFCUDA_cusparseDcsrsm_analysis:
            return handle_HFCUDA_cusparseDcsrsm_analysis();
        case HFCUDA_cusparseDcsrsm_solve:
            return handle_HFCUDA_cusparseDcsrsm_solve();
        case HFCUDA_cusparseDcsrsv2_analysis:
            return handle_HFCUDA_cusparseDcsrsv2_analysis();
        case HFCUDA_cusparseDcsrsv2_bufferSize:
            return handle_HFCUDA_cusparseDcsrsv2_bufferSize();
        case HFCUDA_cusparseDcsrsv2_solve:
            return handle_HFCUDA_cusparseDcsrsv2_solve();
        case HFCUDA_cusparseDcsrsv_analysis:
            return handle_HFCUDA_cusparseDcsrsv_analysis();
        case HFCUDA_cusparseDcsrsv_solve:
            return handle_HFCUDA_cusparseDcsrsv_solve();
        case HFCUDA_cusparseDcsru2csr:
            return handle_HFCUDA_cusparseDcsru2csr();
        case HFCUDA_cusparseDcsru2csr_bufferSizeExt:
            return handle_HFCUDA_cusparseDcsru2csr_bufferSizeExt();
        case HFCUDA_cusparseDdense2csc:
            return handle_HFCUDA_cusparseDdense2csc();
        case HFCUDA_cusparseDdense2csr:
            return handle_HFCUDA_cusparseDdense2csr();
        case HFCUDA_cusparseDdense2hyb:
            return handle_HFCUDA_cusparseDdense2hyb();
        case HFCUDA_cusparseDdoti:
            return handle_HFCUDA_cusparseDdoti();
        case HFCUDA_cusparseDestroy:
            return handle_HFCUDA_cusparseDestroy();
        case HFCUDA_cusparseDestroyBsric02Info:
            return handle_HFCUDA_cusparseDestroyBsric02Info();
        case HFCUDA_cusparseDestroyBsrilu02Info:
            return handle_HFCUDA_cusparseDestroyBsrilu02Info();
        case HFCUDA_cusparseDestroyBsrsm2Info:
            return handle_HFCUDA_cusparseDestroyBsrsm2Info();
        case HFCUDA_cusparseDestroyBsrsv2Info:
            return handle_HFCUDA_cusparseDestroyBsrsv2Info();
        case HFCUDA_cusparseDestroyCsrgemm2Info:
            return handle_HFCUDA_cusparseDestroyCsrgemm2Info();
        case HFCUDA_cusparseDestroyCsric02Info:
            return handle_HFCUDA_cusparseDestroyCsric02Info();
        case HFCUDA_cusparseDestroyCsrilu02Info:
            return handle_HFCUDA_cusparseDestroyCsrilu02Info();
        case HFCUDA_cusparseDestroyCsrsv2Info:
            return handle_HFCUDA_cusparseDestroyCsrsv2Info();
        case HFCUDA_cusparseDestroyCsru2csrInfo:
            return handle_HFCUDA_cusparseDestroyCsru2csrInfo();
        case HFCUDA_cusparseDestroyHybMat:
            return handle_HFCUDA_cusparseDestroyHybMat();
        case HFCUDA_cusparseDestroyMatDescr:
            return handle_HFCUDA_cusparseDestroyMatDescr();
        case HFCUDA_cusparseDestroyPruneInfo:
            return handle_HFCUDA_cusparseDestroyPruneInfo();
        case HFCUDA_cusparseDestroySolveAnalysisInfo:
            return handle_HFCUDA_cusparseDestroySolveAnalysisInfo();
        case HFCUDA_cusparseDgebsr2csr:
            return handle_HFCUDA_cusparseDgebsr2csr();
        case HFCUDA_cusparseDgebsr2gebsc:
            return handle_HFCUDA_cusparseDgebsr2gebsc();
        case HFCUDA_cusparseDgebsr2gebsc_bufferSize:
            return handle_HFCUDA_cusparseDgebsr2gebsc_bufferSize();
        case HFCUDA_cusparseDgebsr2gebsr:
            return handle_HFCUDA_cusparseDgebsr2gebsr();
        case HFCUDA_cusparseDgebsr2gebsr_bufferSize:
            return handle_HFCUDA_cusparseDgebsr2gebsr_bufferSize();
        case HFCUDA_cusparseDgemmi:
            return handle_HFCUDA_cusparseDgemmi();
        case HFCUDA_cusparseDgemvi:
            return handle_HFCUDA_cusparseDgemvi();
        case HFCUDA_cusparseDgemvi_bufferSize:
            return handle_HFCUDA_cusparseDgemvi_bufferSize();
        case HFCUDA_cusparseDgthr:
            return handle_HFCUDA_cusparseDgthr();
        case HFCUDA_cusparseDgthrz:
            return handle_HFCUDA_cusparseDgthrz();
        case HFCUDA_cusparseDhyb2csc:
            return handle_HFCUDA_cusparseDhyb2csc();
        case HFCUDA_cusparseDhyb2csr:
            return handle_HFCUDA_cusparseDhyb2csr();
        case HFCUDA_cusparseDhyb2dense:
            return handle_HFCUDA_cusparseDhyb2dense();
        case HFCUDA_cusparseDhybmv:
            return handle_HFCUDA_cusparseDhybmv();
        case HFCUDA_cusparseDhybsv_analysis:
            return handle_HFCUDA_cusparseDhybsv_analysis();
        case HFCUDA_cusparseDhybsv_solve:
            return handle_HFCUDA_cusparseDhybsv_solve();
        case HFCUDA_cusparseDnnz:
            return handle_HFCUDA_cusparseDnnz();
        case HFCUDA_cusparseDnnz_compress:
            return handle_HFCUDA_cusparseDnnz_compress();
        case HFCUDA_cusparseDpruneCsr2csr:
            return handle_HFCUDA_cusparseDpruneCsr2csr();
        case HFCUDA_cusparseDpruneCsr2csrByPercentage:
            return handle_HFCUDA_cusparseDpruneCsr2csrByPercentage();
        case HFCUDA_cusparseDpruneCsr2csrByPercentage_bufferSizeExt:
            return handle_HFCUDA_cusparseDpruneCsr2csrByPercentage_bufferSizeExt();
        case HFCUDA_cusparseDpruneCsr2csrNnz:
            return handle_HFCUDA_cusparseDpruneCsr2csrNnz();
        case HFCUDA_cusparseDpruneCsr2csrNnzByPercentage:
            return handle_HFCUDA_cusparseDpruneCsr2csrNnzByPercentage();
        case HFCUDA_cusparseDpruneCsr2csr_bufferSizeExt:
            return handle_HFCUDA_cusparseDpruneCsr2csr_bufferSizeExt();
        case HFCUDA_cusparseDpruneDense2csr:
            return handle_HFCUDA_cusparseDpruneDense2csr();
        case HFCUDA_cusparseDpruneDense2csrByPercentage:
            return handle_HFCUDA_cusparseDpruneDense2csrByPercentage();
        case HFCUDA_cusparseDpruneDense2csrByPercentage_bufferSizeExt:
            return handle_HFCUDA_cusparseDpruneDense2csrByPercentage_bufferSizeExt();
        case HFCUDA_cusparseDpruneDense2csrNnz:
            return handle_HFCUDA_cusparseDpruneDense2csrNnz();
        case HFCUDA_cusparseDpruneDense2csrNnzByPercentage:
            return handle_HFCUDA_cusparseDpruneDense2csrNnzByPercentage();
        case HFCUDA_cusparseDpruneDense2csr_bufferSizeExt:
            return handle_HFCUDA_cusparseDpruneDense2csr_bufferSizeExt();
        case HFCUDA_cusparseDroti:
            return handle_HFCUDA_cusparseDroti();
        case HFCUDA_cusparseDsctr:
            return handle_HFCUDA_cusparseDsctr();
        case HFCUDA_cusparseGetMatDiagType:
            return handle_HFCUDA_cusparseGetMatDiagType();
        case HFCUDA_cusparseGetMatFillMode:
            return handle_HFCUDA_cusparseGetMatFillMode();
        case HFCUDA_cusparseGetMatIndexBase:
            return handle_HFCUDA_cusparseGetMatIndexBase();
        case HFCUDA_cusparseGetMatType:
            return handle_HFCUDA_cusparseGetMatType();
        case HFCUDA_cusparseGetStream:
            return handle_HFCUDA_cusparseGetStream();
        case HFCUDA_cusparseGetVersion:
            return handle_HFCUDA_cusparseGetVersion();
        case HFCUDA_cusparseSaxpyi:
            return handle_HFCUDA_cusparseSaxpyi();
        case HFCUDA_cusparseSbsr2csr:
            return handle_HFCUDA_cusparseSbsr2csr();
        case HFCUDA_cusparseSbsrmm:
            return handle_HFCUDA_cusparseSbsrmm();
        case HFCUDA_cusparseSbsrmv:
            return handle_HFCUDA_cusparseSbsrmv();
        case HFCUDA_cusparseSbsrsm2_analysis:
            return handle_HFCUDA_cusparseSbsrsm2_analysis();
        case HFCUDA_cusparseSbsrsm2_bufferSize:
            return handle_HFCUDA_cusparseSbsrsm2_bufferSize();
        case HFCUDA_cusparseSbsrsm2_solve:
            return handle_HFCUDA_cusparseSbsrsm2_solve();
        case HFCUDA_cusparseSbsrsv2_analysis:
            return handle_HFCUDA_cusparseSbsrsv2_analysis();
        case HFCUDA_cusparseSbsrsv2_bufferSize:
            return handle_HFCUDA_cusparseSbsrsv2_bufferSize();
        case HFCUDA_cusparseSbsrsv2_solve:
            return handle_HFCUDA_cusparseSbsrsv2_solve();
        case HFCUDA_cusparseSbsrxmv:
            return handle_HFCUDA_cusparseSbsrxmv();
        case HFCUDA_cusparseScsc2dense:
            return handle_HFCUDA_cusparseScsc2dense();
        case HFCUDA_cusparseScsc2hyb:
            return handle_HFCUDA_cusparseScsc2hyb();
        case HFCUDA_cusparseScsr2bsr:
            return handle_HFCUDA_cusparseScsr2bsr();
        case HFCUDA_cusparseScsr2csc:
            return handle_HFCUDA_cusparseScsr2csc();
        case HFCUDA_cusparseScsr2csr_compress:
            return handle_HFCUDA_cusparseScsr2csr_compress();
        case HFCUDA_cusparseScsr2csru:
            return handle_HFCUDA_cusparseScsr2csru();
        case HFCUDA_cusparseScsr2dense:
            return handle_HFCUDA_cusparseScsr2dense();
        case HFCUDA_cusparseScsr2gebsr:
            return handle_HFCUDA_cusparseScsr2gebsr();
        case HFCUDA_cusparseScsr2gebsr_bufferSize:
            return handle_HFCUDA_cusparseScsr2gebsr_bufferSize();
        case HFCUDA_cusparseScsr2hyb:
            return handle_HFCUDA_cusparseScsr2hyb();
        case HFCUDA_cusparseScsrcolor:
            return handle_HFCUDA_cusparseScsrcolor();
        case HFCUDA_cusparseScsrgeam:
            return handle_HFCUDA_cusparseScsrgeam();
        case HFCUDA_cusparseScsrgemm:
            return handle_HFCUDA_cusparseScsrgemm();
        case HFCUDA_cusparseScsrgemm2:
            return handle_HFCUDA_cusparseScsrgemm2();
        case HFCUDA_cusparseScsrgemm2_bufferSizeExt:
            return handle_HFCUDA_cusparseScsrgemm2_bufferSizeExt();
        case HFCUDA_cusparseScsrmm:
            return handle_HFCUDA_cusparseScsrmm();
        case HFCUDA_cusparseScsrmm2:
            return handle_HFCUDA_cusparseScsrmm2();
        case HFCUDA_cusparseScsrmv:
            return handle_HFCUDA_cusparseScsrmv();
        case HFCUDA_cusparseScsrmv_mp:
            return handle_HFCUDA_cusparseScsrmv_mp();
        case HFCUDA_cusparseScsrsm_analysis:
            return handle_HFCUDA_cusparseScsrsm_analysis();
        case HFCUDA_cusparseScsrsm_solve:
            return handle_HFCUDA_cusparseScsrsm_solve();
        case HFCUDA_cusparseScsrsv2_analysis:
            return handle_HFCUDA_cusparseScsrsv2_analysis();
        case HFCUDA_cusparseScsrsv2_bufferSize:
            return handle_HFCUDA_cusparseScsrsv2_bufferSize();
        case HFCUDA_cusparseScsrsv2_solve:
            return handle_HFCUDA_cusparseScsrsv2_solve();
        case HFCUDA_cusparseScsrsv_analysis:
            return handle_HFCUDA_cusparseScsrsv_analysis();
        case HFCUDA_cusparseScsrsv_solve:
            return handle_HFCUDA_cusparseScsrsv_solve();
        case HFCUDA_cusparseScsru2csr:
            return handle_HFCUDA_cusparseScsru2csr();
        case HFCUDA_cusparseScsru2csr_bufferSizeExt:
            return handle_HFCUDA_cusparseScsru2csr_bufferSizeExt();
        case HFCUDA_cusparseSdense2csc:
            return handle_HFCUDA_cusparseSdense2csc();
        case HFCUDA_cusparseSdense2csr:
            return handle_HFCUDA_cusparseSdense2csr();
        case HFCUDA_cusparseSdense2hyb:
            return handle_HFCUDA_cusparseSdense2hyb();
        case HFCUDA_cusparseSdoti:
            return handle_HFCUDA_cusparseSdoti();
        case HFCUDA_cusparseSetMatDiagType:
            return handle_HFCUDA_cusparseSetMatDiagType();
        case HFCUDA_cusparseSetMatFillMode:
            return handle_HFCUDA_cusparseSetMatFillMode();
        case HFCUDA_cusparseSetMatIndexBase:
            return handle_HFCUDA_cusparseSetMatIndexBase();
        case HFCUDA_cusparseSetMatType:
            return handle_HFCUDA_cusparseSetMatType();
        case HFCUDA_cusparseSetPointerMode:
            return handle_HFCUDA_cusparseSetPointerMode();
        case HFCUDA_cusparseSetStream:
            return handle_HFCUDA_cusparseSetStream();
        case HFCUDA_cusparseSgebsr2csr:
            return handle_HFCUDA_cusparseSgebsr2csr();
        case HFCUDA_cusparseSgebsr2gebsc:
            return handle_HFCUDA_cusparseSgebsr2gebsc();
        case HFCUDA_cusparseSgebsr2gebsc_bufferSize:
            return handle_HFCUDA_cusparseSgebsr2gebsc_bufferSize();
        case HFCUDA_cusparseSgebsr2gebsr:
            return handle_HFCUDA_cusparseSgebsr2gebsr();
        case HFCUDA_cusparseSgebsr2gebsr_bufferSize:
            return handle_HFCUDA_cusparseSgebsr2gebsr_bufferSize();
        case HFCUDA_cusparseSgemmi:
            return handle_HFCUDA_cusparseSgemmi();
        case HFCUDA_cusparseSgemvi:
            return handle_HFCUDA_cusparseSgemvi();
        case HFCUDA_cusparseSgemvi_bufferSize:
            return handle_HFCUDA_cusparseSgemvi_bufferSize();
        case HFCUDA_cusparseSgthr:
            return handle_HFCUDA_cusparseSgthr();
        case HFCUDA_cusparseSgthrz:
            return handle_HFCUDA_cusparseSgthrz();
        case HFCUDA_cusparseShyb2csc:
            return handle_HFCUDA_cusparseShyb2csc();
        case HFCUDA_cusparseShyb2csr:
            return handle_HFCUDA_cusparseShyb2csr();
        case HFCUDA_cusparseShyb2dense:
            return handle_HFCUDA_cusparseShyb2dense();
        case HFCUDA_cusparseShybmv:
            return handle_HFCUDA_cusparseShybmv();
        case HFCUDA_cusparseShybsv_analysis:
            return handle_HFCUDA_cusparseShybsv_analysis();
        case HFCUDA_cusparseShybsv_solve:
            return handle_HFCUDA_cusparseShybsv_solve();
        case HFCUDA_cusparseSnnz:
            return handle_HFCUDA_cusparseSnnz();
        case HFCUDA_cusparseSnnz_compress:
            return handle_HFCUDA_cusparseSnnz_compress();
        case HFCUDA_cusparseSpruneCsr2csr:
            return handle_HFCUDA_cusparseSpruneCsr2csr();
        case HFCUDA_cusparseSpruneCsr2csrByPercentage:
            return handle_HFCUDA_cusparseSpruneCsr2csrByPercentage();
        case HFCUDA_cusparseSpruneCsr2csrByPercentage_bufferSizeExt:
            return handle_HFCUDA_cusparseSpruneCsr2csrByPercentage_bufferSizeExt();
        case HFCUDA_cusparseSpruneCsr2csrNnz:
            return handle_HFCUDA_cusparseSpruneCsr2csrNnz();
        case HFCUDA_cusparseSpruneCsr2csrNnzByPercentage:
            return handle_HFCUDA_cusparseSpruneCsr2csrNnzByPercentage();
        case HFCUDA_cusparseSpruneCsr2csr_bufferSizeExt:
            return handle_HFCUDA_cusparseSpruneCsr2csr_bufferSizeExt();
        case HFCUDA_cusparseSpruneDense2csr:
            return handle_HFCUDA_cusparseSpruneDense2csr();
        case HFCUDA_cusparseSpruneDense2csrByPercentage:
            return handle_HFCUDA_cusparseSpruneDense2csrByPercentage();
        case HFCUDA_cusparseSpruneDense2csrByPercentage_bufferSizeExt:
            return handle_HFCUDA_cusparseSpruneDense2csrByPercentage_bufferSizeExt();
        case HFCUDA_cusparseSpruneDense2csrNnz:
            return handle_HFCUDA_cusparseSpruneDense2csrNnz();
        case HFCUDA_cusparseSpruneDense2csrNnzByPercentage:
            return handle_HFCUDA_cusparseSpruneDense2csrNnzByPercentage();
        case HFCUDA_cusparseSpruneDense2csr_bufferSizeExt:
            return handle_HFCUDA_cusparseSpruneDense2csr_bufferSizeExt();
        case HFCUDA_cusparseSroti:
            return handle_HFCUDA_cusparseSroti();
        case HFCUDA_cusparseSsctr:
            return handle_HFCUDA_cusparseSsctr();
        case HFCUDA_cusparseXbsrsm2_zeroPivot:
            return handle_HFCUDA_cusparseXbsrsm2_zeroPivot();
        case HFCUDA_cusparseXbsrsv2_zeroPivot:
            return handle_HFCUDA_cusparseXbsrsv2_zeroPivot();
        case HFCUDA_cusparseXcoo2csr:
            return handle_HFCUDA_cusparseXcoo2csr();
        case HFCUDA_cusparseXcoosortByColumn:
            return handle_HFCUDA_cusparseXcoosortByColumn();
        case HFCUDA_cusparseXcoosortByRow:
            return handle_HFCUDA_cusparseXcoosortByRow();
        case HFCUDA_cusparseXcoosort_bufferSizeExt:
            return handle_HFCUDA_cusparseXcoosort_bufferSizeExt();
        case HFCUDA_cusparseXcscsort:
            return handle_HFCUDA_cusparseXcscsort();
        case HFCUDA_cusparseXcscsort_bufferSizeExt:
            return handle_HFCUDA_cusparseXcscsort_bufferSizeExt();
        case HFCUDA_cusparseXcsr2bsrNnz:
            return handle_HFCUDA_cusparseXcsr2bsrNnz();
        case HFCUDA_cusparseXcsr2coo:
            return handle_HFCUDA_cusparseXcsr2coo();
        case HFCUDA_cusparseXcsr2gebsrNnz:
            return handle_HFCUDA_cusparseXcsr2gebsrNnz();
        case HFCUDA_cusparseXcsrgeamNnz:
            return handle_HFCUDA_cusparseXcsrgeamNnz();
        case HFCUDA_cusparseXcsrgemm2Nnz:
            return handle_HFCUDA_cusparseXcsrgemm2Nnz();
        case HFCUDA_cusparseXcsrgemmNnz:
            return handle_HFCUDA_cusparseXcsrgemmNnz();
        case HFCUDA_cusparseXcsrsort:
            return handle_HFCUDA_cusparseXcsrsort();
        case HFCUDA_cusparseXcsrsort_bufferSizeExt:
            return handle_HFCUDA_cusparseXcsrsort_bufferSizeExt();
        case HFCUDA_cusparseXcsrsv2_zeroPivot:
            return handle_HFCUDA_cusparseXcsrsv2_zeroPivot();
        case HFCUDA_cusparseXgebsr2gebsrNnz:
            return handle_HFCUDA_cusparseXgebsr2gebsrNnz();
        case HFCUDA_cusparseZaxpyi:
            return handle_HFCUDA_cusparseZaxpyi();
        case HFCUDA_cusparseZbsr2csr:
            return handle_HFCUDA_cusparseZbsr2csr();
        case HFCUDA_cusparseZbsrmm:
            return handle_HFCUDA_cusparseZbsrmm();
        case HFCUDA_cusparseZbsrmv:
            return handle_HFCUDA_cusparseZbsrmv();
        case HFCUDA_cusparseZbsrsm2_analysis:
            return handle_HFCUDA_cusparseZbsrsm2_analysis();
        case HFCUDA_cusparseZbsrsm2_bufferSize:
            return handle_HFCUDA_cusparseZbsrsm2_bufferSize();
        case HFCUDA_cusparseZbsrsm2_solve:
            return handle_HFCUDA_cusparseZbsrsm2_solve();
        case HFCUDA_cusparseZbsrsv2_analysis:
            return handle_HFCUDA_cusparseZbsrsv2_analysis();
        case HFCUDA_cusparseZbsrsv2_bufferSize:
            return handle_HFCUDA_cusparseZbsrsv2_bufferSize();
        case HFCUDA_cusparseZbsrsv2_solve:
            return handle_HFCUDA_cusparseZbsrsv2_solve();
        case HFCUDA_cusparseZbsrxmv:
            return handle_HFCUDA_cusparseZbsrxmv();
        case HFCUDA_cusparseZcsc2dense:
            return handle_HFCUDA_cusparseZcsc2dense();
        case HFCUDA_cusparseZcsc2hyb:
            return handle_HFCUDA_cusparseZcsc2hyb();
        case HFCUDA_cusparseZcsr2bsr:
            return handle_HFCUDA_cusparseZcsr2bsr();
        case HFCUDA_cusparseZcsr2csc:
            return handle_HFCUDA_cusparseZcsr2csc();
        case HFCUDA_cusparseZcsr2csr_compress:
            return handle_HFCUDA_cusparseZcsr2csr_compress();
        case HFCUDA_cusparseZcsr2csru:
            return handle_HFCUDA_cusparseZcsr2csru();
        case HFCUDA_cusparseZcsr2dense:
            return handle_HFCUDA_cusparseZcsr2dense();
        case HFCUDA_cusparseZcsr2gebsr:
            return handle_HFCUDA_cusparseZcsr2gebsr();
        case HFCUDA_cusparseZcsr2gebsr_bufferSize:
            return handle_HFCUDA_cusparseZcsr2gebsr_bufferSize();
        case HFCUDA_cusparseZcsr2hyb:
            return handle_HFCUDA_cusparseZcsr2hyb();
        case HFCUDA_cusparseZcsrcolor:
            return handle_HFCUDA_cusparseZcsrcolor();
        case HFCUDA_cusparseZcsrgeam:
            return handle_HFCUDA_cusparseZcsrgeam();
        case HFCUDA_cusparseZcsrgemm:
            return handle_HFCUDA_cusparseZcsrgemm();
        case HFCUDA_cusparseZcsrgemm2:
            return handle_HFCUDA_cusparseZcsrgemm2();
        case HFCUDA_cusparseZcsrgemm2_bufferSizeExt:
            return handle_HFCUDA_cusparseZcsrgemm2_bufferSizeExt();
        case HFCUDA_cusparseZcsrmm:
            return handle_HFCUDA_cusparseZcsrmm();
        case HFCUDA_cusparseZcsrmm2:
            return handle_HFCUDA_cusparseZcsrmm2();
        case HFCUDA_cusparseZcsrmv:
            return handle_HFCUDA_cusparseZcsrmv();
        case HFCUDA_cusparseZcsrmv_mp:
            return handle_HFCUDA_cusparseZcsrmv_mp();
        case HFCUDA_cusparseZcsrsm_analysis:
            return handle_HFCUDA_cusparseZcsrsm_analysis();
        case HFCUDA_cusparseZcsrsm_solve:
            return handle_HFCUDA_cusparseZcsrsm_solve();
        case HFCUDA_cusparseZcsrsv2_analysis:
            return handle_HFCUDA_cusparseZcsrsv2_analysis();
        case HFCUDA_cusparseZcsrsv2_bufferSize:
            return handle_HFCUDA_cusparseZcsrsv2_bufferSize();
        case HFCUDA_cusparseZcsrsv2_solve:
            return handle_HFCUDA_cusparseZcsrsv2_solve();
        case HFCUDA_cusparseZcsrsv_analysis:
            return handle_HFCUDA_cusparseZcsrsv_analysis();
        case HFCUDA_cusparseZcsrsv_solve:
            return handle_HFCUDA_cusparseZcsrsv_solve();
        case HFCUDA_cusparseZcsru2csr:
            return handle_HFCUDA_cusparseZcsru2csr();
        case HFCUDA_cusparseZcsru2csr_bufferSizeExt:
            return handle_HFCUDA_cusparseZcsru2csr_bufferSizeExt();
        case HFCUDA_cusparseZdense2csc:
            return handle_HFCUDA_cusparseZdense2csc();
        case HFCUDA_cusparseZdense2csr:
            return handle_HFCUDA_cusparseZdense2csr();
        case HFCUDA_cusparseZdense2hyb:
            return handle_HFCUDA_cusparseZdense2hyb();
        case HFCUDA_cusparseZdotci:
            return handle_HFCUDA_cusparseZdotci();
        case HFCUDA_cusparseZdoti:
            return handle_HFCUDA_cusparseZdoti();
        case HFCUDA_cusparseZgebsr2csr:
            return handle_HFCUDA_cusparseZgebsr2csr();
        case HFCUDA_cusparseZgebsr2gebsc:
            return handle_HFCUDA_cusparseZgebsr2gebsc();
        case HFCUDA_cusparseZgebsr2gebsc_bufferSize:
            return handle_HFCUDA_cusparseZgebsr2gebsc_bufferSize();
        case HFCUDA_cusparseZgebsr2gebsr:
            return handle_HFCUDA_cusparseZgebsr2gebsr();
        case HFCUDA_cusparseZgebsr2gebsr_bufferSize:
            return handle_HFCUDA_cusparseZgebsr2gebsr_bufferSize();
        case HFCUDA_cusparseZgemmi:
            return handle_HFCUDA_cusparseZgemmi();
        case HFCUDA_cusparseZgemvi:
            return handle_HFCUDA_cusparseZgemvi();
        case HFCUDA_cusparseZgemvi_bufferSize:
            return handle_HFCUDA_cusparseZgemvi_bufferSize();
        case HFCUDA_cusparseZgthr:
            return handle_HFCUDA_cusparseZgthr();
        case HFCUDA_cusparseZgthrz:
            return handle_HFCUDA_cusparseZgthrz();
        case HFCUDA_cusparseZhyb2csc:
            return handle_HFCUDA_cusparseZhyb2csc();
        case HFCUDA_cusparseZhyb2csr:
            return handle_HFCUDA_cusparseZhyb2csr();
        case HFCUDA_cusparseZhyb2dense:
            return handle_HFCUDA_cusparseZhyb2dense();
        case HFCUDA_cusparseZhybmv:
            return handle_HFCUDA_cusparseZhybmv();
        case HFCUDA_cusparseZhybsv_analysis:
            return handle_HFCUDA_cusparseZhybsv_analysis();
        case HFCUDA_cusparseZhybsv_solve:
            return handle_HFCUDA_cusparseZhybsv_solve();
        case HFCUDA_cusparseZnnz:
            return handle_HFCUDA_cusparseZnnz();
        case HFCUDA_cusparseZnnz_compress:
            return handle_HFCUDA_cusparseZnnz_compress();
        case HFCUDA_cusparseZsctr:
            return handle_HFCUDA_cusparseZsctr();
    /* !!! ^^^ AUTO GENERATED ^^^ !!! */

        default:
            hferr("[daemon] invalid function code: %d\n", function);
            return HFERR;
    }
}

void* handler(void* arg)
{
    hfinf("[daemon] handler started\n");

    args_t* args = (args_t*) arg;

    hfcheck(hfcuda_comm_set(&args->conn));
    hfcheck(hfcuda_shlib_load()); // why do we always load the same library? -> either do it in the main once or supply string ..

    while (true) {
        hfcuda_function_t function = NONE;
        clockme("");
        clockme("(D) waiting for opcode");
        hfcheck(hfcuda_comm_recv(&function, sizeof(hfcuda_function_t)));
        clockme("(D) got opcode!!!");
        if ( function == NONE )
            break;
        hfcheck(hf_handle(function));
    }

    hfcomm_free(&args->conn);
    free(arg);
    
    hfinf("[daemon] handler terminating!\n");
    
    return NULL;
}

#include <signal.h>

void sig_handler(int signo)
{
    (void) signo; // avoid compiler warning
    printf("\n");
    clock_show();
    exit(0);
}

int main(void)
{
    hfinf("[daemon] started\n");
    signal(SIGINT, sig_handler);

    int gl_hfcuda_comm_port;
    hfcomm_type_t gl_hfcuda_comm_type;
    hfcheck(hfcuda_comm_init(&gl_hfcuda_comm_port,
                             &gl_hfcuda_comm_type));
    hfcheck(hfcuda_shlib_init());

    const char* host;
    hfcheck(hfenv(HFCUDA_ENV_HOST, &host, HFCUDA_DEF_HOST));
    hfcheck(hfcomm_server_prepare(&server,
                                  (char*) host,
                                  gl_hfcuda_comm_port,
                                  gl_hfcuda_comm_type));
    hfinf("[daemon] prepared\n");

    while (true) {
        hfinf("[daemon] waiting for new connection...\n");
        args_t* args = (args_t*) malloc (sizeof(*args));

        hfcheck(hfcomm_server_accept(&server, &args->conn));
        hfinf("[daemon] connection accepted\n");

        pthread_create(&args->thread, NULL, &handler, args);
        hfinf("[daemon] handler thread started\n");
    }

    return 0;
}



